GM.ZELyrics = {
	["against the tide cut louder 44100.mp3"] = {
		{time = 1.4, text = "Oh father, why have they forsaken me?"},
		{time = 5.5, text = "You warned me that they would"},
		{time = 7.7, text = "With curses passing down the bloodline"},
		{time = 10.7, text = "Unspoken and misunderstood"},
		{time = 13.7, text = "We're losing light"},
		{time = 15.0, text = "And strength of will"},
		{time = 16.8, text = "The darkened depths beckoning still"},
		{time = 19.6, text = "Then we hold on against the tide"},

		{time = 50.5, text = "Beneath the storm you're left to fight alone"},
		{time = 56.5, text = "Remember son, you're reaping what you've sown"},
		{time = 62.6, text = "Under the waves and sinking like a stone"},
		{time = 68.4, text = "I'm sorry son, you're reaping what you've sown"},
		{time = 74.5, text = "Beneath the storm you're left to fight alone"},
		{time = 80.5, text = "Remember son, you're reaping what you've sown"},
		{time = 86.6, text = "Under the waves and sinking like a stone"},
		{time = 92.4, text = "I'm sorry son, you're reaping what you've sown"},
		{time = 96.8, text = "You're reaping what you've sown"},

		{time = 105.6, text = "You're reaping what you've sown"},
		{time = 117.6, text = "You're reaping what you've sown (You're reaping what you've sown)"},

		{time = 123.9, text = "We're slowly losing ground"},
		{time = 126.5, text = "And hope is harder to maintain"},
		{time = 129.9, text = "When all the prayers we prayed feel lost like tears in the rain"},
		{time = 136.0, text = "The water's pouring  down"},
		{time = 138.4, text = "The moon's eclipsing the sun"},
		{time = 142.0, text = "The ending that we knew would come has finally begun"},

		{time = 151.6, text = "(Help me hold out)"},
		{time = 153.9, text = "(You're reaping what you've sown!)"},
		{time = 156.9, text = "It's finally begun"},
		{time = 163.1, text = "You're reaping what you've sown (You're reaping what you've sown)"},
		{time = 169.7, text = "(Help me hold out)"},
		{time = 173.5, text = "I'm sorry son, you're reaping what you've sown"},
		{time = 177.7, text = "You're reaping what you've sown"},
		{time = 180.9, text = "(You're reaping what you've sown)"},
	},
	["jericho circle of dust remix cut louder.mp3"] = {
		{time = 9.5, text = "You build 'em up"},
		{time = 11.6, text = "You layer stone on stone"},
		{time = 13.9, text = "You build 'em high to keep out your enemies"},
		{time = 18.3, text = "The sky grow dark"},
		{time = 20.4, text = "The earth is trembling"},
		{time = 22.5, text = "An unhappy ending to your final fantasy"},

		{time = 32.6, text = "When your walls fall like Jericho"},

		{time = 53.0, text = "You feel so safe insi-"},
		{time = 55.2, text = "The walls you fortified"},
		{time = 57.3, text = "Supremacy implied"},
		{time = 59.3, text = "Who dares to overthrow?"},
		{time = 61.9, text = "Arrogance justifi-"},
		{time = 63.8, text = "Self-importance amplified"},
		{time = 66.3, text = "It's down you go"},
		{time = 67.6, text = "When your walls fall like Jericho"},

		{time = 76.4, text = "When your walls fall like Jericho"},
		{time = 80.4, text = "(This is over)"},
		{time = 83.2, text = "We'll all enjoy the show"},
		{time = 85.1, text = "When your walls fall like Jericho"},

		{time = 90.3, text = "(In a grim new age of warfare)"},
		{time = 92.2, text = "(Today's fighting men must be taught survival on an atomic battlefield)"},

		{time = 96.5, text = "10..."},
		{time = 97.7, text = "10, 9..."},
		{time = 98.8, text = "10, 9, 8..."},
		{time = 99.9, text = "10, 9, 8, 7..."},
		{time = 100.9, text = "10, 9, 8, 7, 6..."},
		{time = 102.0, text = "10, 9, 8, 7, 6, 5..."},
		{time = 103.1, text = "10, 9, 8, 7, 6, 5, 4..."},
		{time = 103.6, text = "10, 9, 8, 7, 6, 5, 4, 3..."},
		{time = 104.2, text = "10, 9, 8, 7, 6, 5, 4, 3, 2..."},
		{time = 104.7, text = "10, 9, 8, 7, 6, 5, 4, 3, 2, 1..."},

		{time = 105.3, text = "You're looking down"},
		{time = 107.7, text = "And feeling so profound"},
		{time = 109.8, text = "You're so impressed by your own false humility"},
		{time = 114.3, text = "The sky decends"},
		{time = 116.4, text = "The ground is rising up"},
		{time = 118.5, text = "An unhappy ending to your sense of deity"},

		{time = 122.9, text = "You feel so safe insi-"},
		{time = 125.1, text = "The walls you fortified"},
		{time = 127.2, text = "Supremacy implied"},
		{time = 129.0, text = "Who dares to overthrow?"},
		{time = 131.7, text = "Arrogance justifi-"},
		{time = 133.6, text = "Self-importance amplified"},
		{time = 136.0, text = "It's down you go"},
		{time = 137.4, text = "When your walls fall like Jericho"},

		{time = 143.7, text = "(This is over, this is over"},
		{time = 152.5, text = "(This is over)"},
		{time = 155.0, text = "When your walls fall like Jericho"},

		{time = 175.3, text = "You feel so safe inside"},
		{time = 179.7, text = "The walls you fortified"},
		{time = 184.2, text = "It's down you go"},
		{time = 187.7, text = "When your walls fall like Jericho"},

		{time = 206.1, text = "(I don't wanna hurt you!)"},
		{time = 208.6, text = "(But you try something and I'll...)"},
		{time = 210.7, text = "(I'll rip your face off!)"},
		{time = 212.3, text = "(I'm gonna kill everyone here.)"},

		{time = 214.6, text = "You feel so safe inside"},
		{time = 216.8, text = "The walls you fortified"},
		{time = 218.9, text = "Supremacy implied"},
		{time = 220.6, text = "Who dares to overthrow?"},
		{time = 223.4, text = "Arrogance justified"},
		{time = 225.3, text = "Self-importance amplified"},
		{time = 227.8, text = "It's down you go"},
		{time = 229.4, text = "We'll all enjoy the show"},
		{time = 231.5, text = "Can't wait to see you go"},
		{time = 233.5, text = "When your walls fall like Jericho"},

		{time = 240.5, text = "You don't frighten me!"},

		{time = 248.3, text = "(This is over, this is over)"},
		{time = 257.3, text = "(This is over, this is over)"},
		{time = 262.0, text = "We'll all enjoy the show"},
		{time = 264.2, text = "It's do-do-down you go"},
		{time = 266.4, text = "Can't wait to see you go"},
		{time = 268.4, text = "When your walls fall like Jericho"},

		{time = 272.7, text = "(I don't wanna hurt you!)"},
		{time = 275.0, text = "(But you try something and I'll...)"},
		{time = 277.4, text = "(I'll rip your face off!)"},
		{time = 280.0, text = "(I'm gonna kill everyone here.)"},
		{time = 283.8, text = "(And this time, make sure they're all dead before you leave.)"},
	},
}