GM.ZELyrics = {
	["against the tide cut louder 44100.mp3"] = {
		{time = 1.4, text = "Oh father, why have they forsaken me?"},
		{time = 5.5, text = "You warned me that they would"},
		{time = 7.7, text = "With curses passing down the bloodline"},
		{time = 10.7, text = "Unspoken and misunderstood"},
		{time = 13.7, text = "We're losing light"},
		{time = 15.0, text = "And strength of will"},
		{time = 16.8, text = "The darkened depths beckoning still"},
		{time = 19.6, text = "Then we hold on against the tide"},

		{time = 50.5, text = "Beneath the storm you're left to fight alone"},
		{time = 56.5, text = "Remember son, you're reaping what you've sown"},
		{time = 62.6, text = "Under the waves and sinking like a stone"},
		{time = 68.4, text = "I'm sorry son, you're reaping what you've sown"},
		{time = 74.5, text = "Beneath the storm you're left to fight alone"},
		{time = 80.5, text = "Remember son, you're reaping what you've sown"},
		{time = 86.6, text = "Under the waves and sinking like a stone"},
		{time = 92.4, text = "I'm sorry son, you're reaping what you've sown"},
		{time = 96.8, text = "You're reaping what you've sown"},

		{time = 105.6, text = "You're reaping what you've sown"},
		{time = 117.6, text = "You're reaping what you've sown (You're reaping what you've sown)"},

		{time = 123.9, text = "We're slowly losing ground"},
		{time = 126.5, text = "And hope is harder to maintain"},
		{time = 129.9, text = "When all the prayers we prayed feel lost like tears in the rain"},
		{time = 136.0, text = "The water's pouring  down"},
		{time = 138.4, text = "The moon's eclipsing the sun"},
		{time = 142.0, text = "The ending that we knew would come has finally begun"},

		{time = 151.6, text = "(Help me hold out)"},
		{time = 153.9, text = "(You're reaping what you've sown!)"},
		{time = 156.9, text = "It's finally begun"},
		{time = 163.1, text = "You're reaping what you've sown (You're reaping what you've sown)"},
		{time = 169.7, text = "(Help me hold out)"},
		{time = 173.5, text = "I'm sorry son, you're reaping what you've sown"},
		{time = 177.7, text = "You're reaping what you've sown"},
		{time = 180.9, text = "(You're reaping what you've sown)"},
	},
	["jericho circle of dust remix cut louder.mp3"] = {
		{time = 9.5, text = "You build 'em up"},
		{time = 11.6, text = "You layer stone on stone"},
		{time = 13.9, text = "You build 'em high to keep out your enemies"},
		{time = 18.3, text = "The sky grow dark"},
		{time = 20.4, text = "The earth is trembling"},
		{time = 22.5, text = "An unhappy ending to your final fantasy"},

		{time = 32.6, text = "When your walls fall like Jericho"},

		{time = 53.0, text = "You feel so safe insi-"},
		{time = 55.2, text = "The walls you fortified"},
		{time = 57.3, text = "Supremacy implied"},
		{time = 59.3, text = "Who dares to overthrow?"},
		{time = 61.9, text = "Arrogance justifi-"},
		{time = 63.8, text = "Self-importance amplified"},
		{time = 66.3, text = "It's down you go"},
		{time = 67.6, text = "When your walls fall like Jericho"},

		{time = 76.4, text = "When your walls fall like Jericho"},
		{time = 80.4, text = "(This is over)"},
		{time = 83.2, text = "We'll all enjoy the show"},
		{time = 85.1, text = "When your walls fall like Jericho"},

		{time = 90.3, text = "(In a grim new age of warfare)"},
		{time = 92.2, text = "(Today's fighting men must be taught survival on an atomic battlefield)"},

		{time = 96.5, text = "10..."},
		{time = 97.7, text = "10, 9..."},
		{time = 98.8, text = "10, 9, 8..."},
		{time = 99.9, text = "10, 9, 8, 7..."},
		{time = 100.9, text = "10, 9, 8, 7, 6..."},
		{time = 102.0, text = "10, 9, 8, 7, 6, 5..."},
		{time = 103.1, text = "10, 9, 8, 7, 6, 5, 4..."},
		{time = 103.6, text = "10, 9, 8, 7, 6, 5, 4, 3..."},
		{time = 104.2, text = "10, 9, 8, 7, 6, 5, 4, 3, 2..."},
		{time = 104.7, text = "10, 9, 8, 7, 6, 5, 4, 3, 2, 1..."},

		{time = 105.3, text = "You're looking down"},
		{time = 107.7, text = "And feeling so profound"},
		{time = 109.8, text = "You're so impressed by your own false humility"},
		{time = 114.3, text = "The sky decends"},
		{time = 116.4, text = "The ground is rising up"},
		{time = 118.5, text = "An unhappy ending to your sense of deity"},

		{time = 122.9, text = "You feel so safe insi-"},
		{time = 125.1, text = "The walls you fortified"},
		{time = 127.2, text = "Supremacy implied"},
		{time = 129.0, text = "Who dares to overthrow?"},
		{time = 131.7, text = "Arrogance justifi-"},
		{time = 133.6, text = "Self-importance amplified"},
		{time = 136.0, text = "It's down you go"},
		{time = 137.4, text = "When your walls fall like Jericho"},

		{time = 143.7, text = "(This is over, this is over"},
		{time = 152.5, text = "(This is over)"},
		{time = 155.0, text = "When your walls fall like Jericho"},

		{time = 175.3, text = "You feel so safe inside"},
		{time = 179.7, text = "The walls you fortified"},
		{time = 184.2, text = "It's down you go"},
		{time = 187.7, text = "When your walls fall like Jericho"},

		{time = 206.1, text = "(I don't wanna hurt you!)"},
		{time = 208.6, text = "(But you try something and I'll...)"},
		{time = 210.7, text = "(I'll rip your face off!)"},
		{time = 212.3, text = "(I'm gonna kill everyone here.)"},

		{time = 214.6, text = "You feel so safe inside"},
		{time = 216.8, text = "The walls you fortified"},
		{time = 218.9, text = "Supremacy implied"},
		{time = 220.6, text = "Who dares to overthrow?"},
		{time = 223.4, text = "Arrogance justified"},
		{time = 225.3, text = "Self-importance amplified"},
		{time = 227.8, text = "It's down you go"},
		{time = 229.4, text = "We'll all enjoy the show"},
		{time = 231.5, text = "Can't wait to see you go"},
		{time = 233.5, text = "When your walls fall like Jericho"},

		{time = 240.5, text = "You don't frighten me!"},

		{time = 248.3, text = "(This is over, this is over)"},
		{time = 257.3, text = "(This is over, this is over)"},
		{time = 262.0, text = "We'll all enjoy the show"},
		{time = 264.2, text = "It's do-do-down you go"},
		{time = 266.4, text = "Can't wait to see you go"},
		{time = 268.4, text = "When your walls fall like Jericho"},

		{time = 272.7, text = "(I don't wanna hurt you!)"},
		{time = 275.0, text = "(But you try something and I'll...)"},
		{time = 277.4, text = "(I'll rip your face off!)"},
		{time = 280.0, text = "(I'm gonna kill everyone here.)"},
		{time = 283.8, text = "(And this time, make sure they're all dead before you leave.)"},
	},
	["children of the sun [louder,44100].mp3"] = {
		{time = 19.1, text = "Fighting and running from turning from who we really are"},
		{time = 23.6, text = "Cannot suppress so let's find the one we have shaped so far"},
		{time = 27.9, text = "Flying too close to the sun as if we're invincible"},
		{time = 32.3, text = "Cannot dictate, dominate the earth that we're living on"},

		{time = 36.7, text = "We can't defy the laws, cut the loss that we consummate"},
		{time = 41.1, text = "Around the world, we grow weaker as we exterminate"},
		{time = 45.4, text = "The only thing that gives, thing that brings air and life to us"},
		{time = 49.8, text = "Wake up one day and find what we got is so serious"},

		{time = 54.3, text = "We are the children of the Sun"},
		{time = 63.1, text = "We are the children of the Sun"},

		{time = 73.7, text = "The human greed and our creed is all that we have to share"},
		{time = 78.2, text = "Knee-deep in tragical, fabrical issues everywhere"},
		{time = 82.4, text = "Cannot replace the one, chase the one that we used to be"},
		{time = 87.0, text = "It isn't how we were, why we're here, what we're meant to be"},

		{time = 91.2, text = "Fighting and running from turning from who we really are"},
		{time = 95.6, text = "Cannot suppress so let's find the one we have shaped so far"},
		{time = 99.9, text = "Flying too close to the sun as if we're invincible"},
		{time = 104.3, text = "Cannot dictate our faith on this earth that we're living on"},

		{time = 107.8, text = "We are the children of the Sun"},
		{time = 114.5, text = "The love for everyone"},
		{time = 119.3, text = "Always on the run"},
		{time = 127.7, text = "The fire in our eyes"},
		{time = 132.1, text = "The passion never dies"},
		{time = 136.7, text = "We're the chosen ones"},
		{time = 140.8, text = "The children of the Sun"},

		{time = 196.2, text = "We are the children of the Sun"},
		{time = 203.0, text = "The love for everyone"},
		{time = 207.7, text = "Always on the run"},
		{time = 216.1, text = "The fire in our eyes"},
		{time = 220.5, text = "The passion never dies"},
		{time = 225.1, text = "We're the chosen ones"},
		{time = 229.3, text = "The children of the Sun"},

		{time = 232.2, text = "We are, we are"},
		{time = 237.3, text = "We are the children of the Sun"},
		{time = 241.0, text = "We are, we are"},
		{time = 246.7, text = "The children of the Sun"},
		{time = 249.8, text = "We are, we are"},
		{time = 254.6, text = "(We are the children)"},
		{time = 260.0, text = "Always on the run"},
	},
	["propane nightmares celldweller remix[louder,44100].mp3"] = {
		{time = 3.3, text = "I know we will be free again"},
		{time = 15.5, text = "Bring it on home"},
		{time = 40.3, text = "Bring it on home"},
		{time = 45.9, text = "Bring it on home"},
		{time = 51.4, text = "Bring it on home"},
		{time = 57.0, text = "Bring it on home"},
		{time = 62.8, text = "Bring it on home"},

		{time = 96.8, text = "Mind is willing, soul remains"},
		{time = 99.6, text = "This woman cannot be saved"},
		{time = 102.4, text = "From the trail into the fire"},
		{time = 107.9, text = "Mind is willing, soul remains"},
		{time = 110.8, text = "This woman cannot be saved"},
		{time = 113.4, text = "From the trail into the fire"},
		{time = 116.2, text = "Anything to bring it on home"},

		{time = 129.9, text = "Much too weak to jump yourself"},
		{time = 132.8, text = "Heal the wounds or crack the shell"},
		{time = 135.4, text = "Lift yourself from what's below"},
		{time = 140.9, text = "Much too weak to jump yourself"},
		{time = 143.7, text = "Heal the wounds or crack the shell"},
		{time = 146.6, text = "Lift yourself from what's below"},
		{time = 149.2, text = "Raise the anchor, bring it on home"},

		{time = 156.2, text = "Bring it on home"},
		{time = 161.6, text = "Bring it on home"},
		{time = 167.3, text = "Bring it on home"},
		{time = 172.8, text = "Bring it on home"},
		{time = 183.7, text = "Bring it on home"},

		{time = 215.4, text = "Something's tearing me down"},
		{time = 219.3, text = "And I can't help but feel it's coming from you"},
		{time = 226.9, text = "She's a gunshot bride, and her trigger cries"},
		{time = 231.8, text = "I just wonder what we've gotten ourselves into"},

		{time = 237.5, text = "In a trail of fire I know we will be free again"},
		{time = 243.1, text = "In the end we will be one"},
		{time = 248.5, text = "In a trail of fire I'll burn before you bury me"},
		{time = 254.0, text = "Set your sights for the sun"},
		{time = 261.1, text = "Bring it on home"},
		{time = 274.8, text = "Bring it on home"},

		{time = 285.9, text = "Bring it on home"},
		{time = 291.4, text = "Bring it on home"},
		{time = 296.9, text = "Bring it on home"},
		{time = 301.0, text = "Mind is willing, soul remains"},
		{time = 306.6, text = "This woman cannot be saved"},
		{time = 312.0, text = "Much too weak to jump yourself"},
		{time = 317.6, text = "Heal the wounds or crack the shell"},
		{time = 323.1, text = "Lift yourself from once below"},
		{time = 328.7, text = "Praise the anger bring it on home"},
	},
}