GM.ZELyrics = {
	["epic_sirens.mp3"] = {
		{time = 23.0, text = "All I hear is sirens"},
		{time = 28.9, text = "What I need is silence"},
		{time = 34.5, text = "Everything is fading"},
		{time = 40.0, text = "Away from me"},
		{time = 46.2, text = "I'm holding on while staring at the ground"},
		{time = 52.2, text = "Rising up to only fall back down"},
		{time = 57.4, text = "This silence screams that crying make no sound"},
		{time = 62.3, text = "And I'm looking down"},
		{time = 65.1, text = "But I never let go"},
		{time = 87.0, text = "But I never let go"},
		{time = 91.0, text = "Woah-oh-eh-oh"},
		{time = 92.6, text = "But I never let go"},
		{time = 96.6, text = "Woah-oh-eh-oh"},
		{time = 98.3, text = "But I never let go"},
		{time = 102.0, text = "Woah-oh-eh-oh"},
		{time = 104.6, text = "The only thing I know is that I'm never letting go"},
		{time = 134.5, text = "I'm holding on while staring at the ground"},
		{time = 140.5, text = "Nothing else can hold me down"},
		{time = 145.8, text = "I'm waiting for the life I used to know"},
		{time = 150.6, text = "And I'm looking down"},
		{time = 153.4, text = "But I never let go"},
		{time = 178.5, text = "But I never let go"},
		{time = 179.3, text = "Woah-oh-eh-oh"},
		{time = 181.4, text = "But I never let go"},
		{time = 184.8, text = "Woah-oh-eh-oh"},
		{time = 186.6, text = "But I never let go"},
		{time = 190.4, text = "Woah-oh-eh-oh"},
		{time = 192.8, text = "The only thing I know is that I'm never letting go"},
	},
}