GM.ZELyrics = {
	["4ex_4_pendulum_the_other_side_a.mp3"] = {
		{time = 0.4, text = "Come on down to the other side"},
		{time = 3.9, text = "Come with us through the gates of hell"},
		{time = 7.4, text = "We will drag you from where you are"},
		{time = 11.1, text = "To where you belong"},
		{time = 14.4, text = "Come on down to the other side"},
		{time = 17.8, text = "Come with us through the gates of hell"},
		{time = 21.3, text = "We will drag you from where you are"},
		{time = 25.0, text = "To where you belong"},

		{time = 28.9, text = "There's nothing to fear"},
		{time = 32.4, text = "Your saviors are here"},
		{time = 35.8, text = "The ship is coming down"},
		{time = 40.7, text = "The ship is coming down, coming down"},
		{time = 41.9, text = "The ship is coming down, coming down, coming down"},

		{time = 43.1, text = "You"},
		{time = 44.1, text = "You, you are so precious"},
		{time = 46.8, text = "A diamond in the rough"},
		{time = 49.5, text = "And when you try to escape"},
		{time = 52.2, text = "I'll be holding on"},
		{time = 54.0, text = "I'll be holding on, holding on"},
		{time = 55.0, text = "I'll be holding on, holding on, holding on"},

		{time = 57.8, text = "But I can't sleep until this is done"},
	},
	["5i_1a_pendulum_bloodsugar.mp3"] = {
		{time = 3.2, text = "Ladies and gentlemen,"},
		{time = 5.5, text = "We understand that you"},
		{time = 8.2, text = "Have come tonight"},
		{time = 10.4, text = "To bare witness to the sound"},
		{time = 13.2, text = "Of drum and bass"},

		{time = 19.1, text = "We regret to announce that this is not the case"},
		{time = 22.9, text = "As instead, we come tonight to bring you,"},
		{time = 25.9, text = "The sonic recreation of the end of the world"},
		{time = 29.2, text = "Ladies and gentlemen,"},
		{time = 30.7, text = "Prepare to hold your color"},

		{time = 74.0, text = "Okay"},
		{time = 74.8, text = "Fuck it"},
		{time = 75.5, text = "I lied"},
		{time = 76.4, text = "It's drum and bass"},
		{time = 77.7, text = "What you gonna do?"},
	},
	["5i_1b_pendulum_slam.mp3"] = {
		{time = 1.5, text = "We're marooned on a small island, in an endless sea"},
		{time = 7.0, text = "Confined to a tiny spit of sand, unable to escape"},
		{time = 15.0, text = "But tonight, on this small planet, on Earth"},
		{time = 24.7, text = "We're going to rock civilisation"},

		{time = 59.4, text = "We're marooned on a small island, in an endless sea"},
		{time = 65.2, text = "Tonight, on this small planet"},
		{time = 70.5, text = "We're going to rock civilisation"},

		{time = 121.1, text = "Is this bass really strong enough?"},
	},
	["5i_2a_pendulum_tarantula.mp3"] = {
		{time = 0.8, text = "Time to fix you up something here right now!"},

		{time = 5.0, text = "Shotta, hitter, serial killer"},
		{time = 7.7, text = "Go-a your funeral and all drink out your liquor"},
		{time = 10.4, text = "When you are bury we a-stand next to vicar"},
		{time = 13.1, text = "Fling on some dirt and make your bury a little quicker"},

		{time = 16.0, text = "Shouldn't test the youth them in the Tommy Hilfiger"},
		{time = 18.7, text = "Hug up ya mama, say sorry to ya poppa"},
		{time = 21.4, text = "All-a get number for ya little sister"},
		{time = 24.4, text = "I true be cold like Alaska, freezer"},

		{time = 26.7, text = "Tarantula"},
		{time = 28.4, text = "Time for the massive come sing ya"},
		{time = 32, text = "Black tarantula"},
		{time = 33.7, text = "Don't play with my style, I might sting ya"},

		{time = 37.5, text = "Black tarantula"},
		{time = 39.2, text = "You want me inject me bacteria"},
		{time = 43.0, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 47.3, text = "Now come fi get some..."},

		{time = 71.1, text = "Shotta, hitter, serial killer"},
		{time = 73.9, text = "Go-a your funeral and all drink out your liquor"},
		{time = 76.6, text = "When you are bury we a-stand next to vicar"},
		{time = 79.4, text = "Fling on some dirt and make your bury a little quicker"},

		{time = 82.1, text = "Shouldn't test the youth them in the Tommy Hilfiger"},
		{time = 84.9, text = "Hug up ya mama, say sorry to ya poppa"},
		{time = 87.7, text = "All-a get number for ya little sister"},
		{time = 90.6, text = "I true be cold like Alaska, freezer"},

		{time = 92.9, text = "Tarantula"},
		{time = 94.6, text = "Time for the massive come sing ya"},
		{time = 98.2, text = "Black tarantula"},
		{time = 99.9, text = "Don't play with my style, I might sting ya"},

		{time = 103.8, text = "Black tarantula"},
		{time = 105.4, text = "You want me inject me bacteria"},
		{time = 109.2, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 113.5, text = "Now come fi get some..."},
	},
	["5i_2b_pendulum_the_fountain.mp3"] = {
		{time = 23.8, text = "You sure, you're right?"},
		{time = 26.6, text = "Well no, you're wrong"},
		{time = 29.7, text = "You don't feel my energy"},
		{time = 32.2, text = "But it won't be long"},
		{time = 34.9, text = "I see the sun"},
		{time = 37.6, text = "Believe the dark"},
		{time = 40.7, text = "Soon I'll disappear"},
		{time = 43.3, text = "But I'll make my mark"},

		{time = 46.4, text = "All these fears and all this love"},
		{time = 51.9, text = "All you've given me is not enough"},
		{time = 57.4, text = "All my dreams and all this stuff"},
		{time = 63.0, text = "All made real and it's not enough"},

		{time = 68.3, text = "Watching, waiting, shaping, faking"},
		{time = 73.7, text = "Shocking, pumping, mocking, stopping"},
		{time = 79.3, text = "Falling, stalling, warning, crawling"},
		{time = 84.7, text = "Rejecting, perfecting, loving, ending"},
	},
	["5i_3_pendulum_self_vs_self.mp3"] = {
		{time = 43.0, text = "If I struggle a lifetime"},
		{time = 46.0, text = "What would my body be?"},
		{time = 48.6, text = "An empty shell"},
		{time = 50.6, text = "On which a demon fed"},

		{time = 53.8, text = "Could be a heavy burden"},
		{time = 56.2, text = "To stay true to your words"},
		{time = 60.0, text = "Speak up"},
		{time = 61.7, text = "I wanna silence everything"},

		{time = 65.5, text = "If I got no plan"},
		{time = 70.7, text = "Doesn't mean that I get what I want for free"},
		{time = 76.4, text = "If I got no meaning"},
		{time = 81.8, text = "Would you force me to a place where I make sense?"},
		{time = 86.6, text = "'Cause nothing lasts forever"},

		{time = 91.7, text = "How do I get home?"},
		{time = 95.0, text = "Everything revolves around me"},
		{time = 97.1, text = "If I can't find myself?"},
		{time = 100.2, text = "It's so completely fake"},

		{time = 102.7, text = "How do I get home?"},
		{time = 106.0, text = "Everything revolves around me"},
		{time = 108.0, text = "If even you can't help"},
		{time = 112.3, text = "Dark nights on my soul"},

		{time = 137.6, text = "I deny failure"},
		{time = 139.9, text = "I ignite"},
		{time = 141.8, text = "Woe is on my misery"},
		{time = 144.7, text = "She wins all their eyes"},

		{time = 147.4, text = "Realize what defies our fate"},
		{time = 150.2, text = "This is not me, this is me"},
		{time = 153.2, text = "So if I struggle a lifetime"},
		{time = 156.0, text = "What good would that do?"},

		{time = 159.1, text = "If I got a plan"},
		{time = 164.7, text = "Doesn't have to stop the feeling inside"},
		{time = 169.9, text = "If I do make sense"},
		{time = 175.4, text = "Would you drag me down?"},
		{time = 180.2, text = "'Cause nothing lasts forever"},

		{time = 207.4, text = "How do I get home?"},
		{time = 210.5, text = "Everything revolves around me"},
		{time = 212.6, text = "If I can't find myself?"},
		{time = 216.0, text = "It's so completely fake"},

		{time = 218.3, text = "How do I get home?"},
		{time = 221.6, text = "Everything revolves around me"},
		{time = 223.6, text = "If even you can't help"},
		{time = 228.0, text = "Dark nights on my soul"},
	},
	["5i_4_pendulum_the_tempest.mp3"] = {
		{time = 5.6, text = "ALRIGHT I NEED YOU TO TAKE A DEEP BREATH"},
		{time = 9.3, text = "EVERYONE INSIDE BRIXTON ACADEMY"},
		{time = 11.6, text = "COME ON"},
		{time = 15.8, text = "ROCK IT UP"},
		{time = 16.8, text = "YEAH"},
		{time = 17.4, text = "YEAH, YEAH"},
		{time = 18.2, text = "YEAH, YEAH, YEAH"},
		{time = 19.0, text = "YEAH, YEAH, YEAH, YEAH"},
		{time = 21.6, text = "GO!"},
		{time = 32.5, text = "SIT DOWN!"},
		{time = 38.7, text = "LOOK UP"},
		{time = 41.4, text = "READY?"},
		{time = 52.5, text = "3..."},
		{time = 53.0, text = "3... 2..."},
		{time = 53.7, text = "3... 2... 1..."},
		{time = 54.4, text = "3... 2... 1... GO"},
		{time = 54.8, text = "3... 2... 1... GO GO"},
		{time = 74.2, text = "SOMEBODY RAISE THE ROOF"},
		{time = 75.9, text = "RAISE THE ROOF"},
	},
	["6zm_a_pendulum_9000_miles.mp3"] = {
		{time = 55.2, text = "Well, it's 9,000 miles back to you"},
		{time = 62.8, text = "Now..."},
		{time = 66.5, text = "And I still feel like home is in"},
		{time = 71.7, text = "Your arms..."},
	},
}