GM.ZELyrics = {
	["muzzy_back_to_you.mp3"] = {
		{time = 22.9, text = "Your vision slips away"},
		{time = 25.6, text = "You're falling down"},
		{time = 28.4, text = "But don't be afraid"},
		{time = 31.0, text = "We're coming back to you"},
		{time = 33.8, text = "We're holding back"},
		{time = 36.5, text = "Until the day"},
		{time = 39.2, text = "You fall again"},
		{time = 42.1, text = "We're coming back to you"},
		{time = 45.2, text = "Oh"},
		{time = 48.1, text = "Oh"},
		{time = 50.6, text = "Oh"},
		{time = 53.0, text = "We're coming back to you"},
		{time = 56.2, text = "Oh"},
		{time = 58.9, text = "Oh"},
		{time = 61.6, text = "Oh"},
		{time = 64.0, text = "We're coming back to you"},
		{time = 66.9, text = "Oh"},
		{time = 69.8, text = "Oh"},
		{time = 72.5, text = "Oh"},
		{time = 75.0, text = "We're coming back to you"},
		{time = 78.1, text = "Oh"},
		{time = 80.9, text = "Oh"},
		{time = 83.5, text = "Oh"},
		{time = 96.8, text = "We're coming back to you"},
		{time = 98.3, text = "We're coming back"},
		{time = 99.7, text = "We're coming back"},
		{time = 101.0, text = "We're coming back"},
		{time = 102.4, text = "We're coming back to you"},
		{time = 107.8, text = "We're coming back to you"},
	},
	["sirens.mp3"] = {
		{time = 23.0, text = "All I hear is sirens"},
		{time = 28.9, text = "What I need is silence"},
		{time = 34.5, text = "Everything is fading away from me"},
		{time = 46.2, text = "I'm holding on while staring at the ground"},
		{time = 52.2, text = "Rising up to only fall back down"},
		{time = 57.4, text = "This silence screams that crying make no sound"},
		{time = 62.3, text = "And I'm looking down"},
		{time = 65.1, text = "But I never let go"},
		{time = 87.0, text = "But I never let go"},
		{time = 91.0, text = "Woah-oh-eh-oh"},
		{time = 92.6, text = "No I never let go"},
		{time = 96.6, text = "Woah-oh-eh-oh"},
		{time = 98.3, text = "But I never let go"},
		{time = 102.0, text = "Woah-oh-eh-oh"},
		{time = 104.6, text = "The only thing I know is that I'm never letting go"},
	},
	["mazare_strand_battlecry.mp3"] = {
		{time = 3.6, text = "Another one hits the water"},
		{time = 6.4, text = "Another one calls my name"},
		{time = 9.0, text = "A daughter has lost her father to the killing game"},
		{time = 14.5, text = "A city burned down to ashes"},
		{time = 17.2, text = "Memories lost in vain"},
		{time = 19.8, text = "It's only gonna make us stronger, as we heal the pain"},
		{time = 25.1, text = "Can you hear the sirens?"},
		{time = 27.7, text = "Can you see the enemy line?"},
		{time = 30.2, text = "I feel it coming closer"},
		{time = 35.6, text = "We're braver than a lion"},
		{time = 38.2, text = "We're stead in our state of mind"},
		{time = 41.0, text = "Keeping our composure"},
		{time = 45.1, text = "Battlecry"},
		{time = 48.7, text = "Can you feel it taking over?"},
		{time = 51.4, text = "Can you feel it taking over?"},
		{time = 56.0, text = "Battlecry"},
		{time = 59.3, text = "Can you feel it taking over?"},
		{time = 62.1, text = "Can you feel it taking over?"},
		{time = 89.1, text = "Can you hear the sirens?"},
		{time = 91.7, text = "Can you see the enemy line?"},
		{time = 94.2, text = "I feel it coming closer"},
		{time = 99.5, text = "We're braver than a lion"},
		{time = 102.2, text = "We're steady in our state of mind"},
		{time = 105.0, text = "Keeping our composure"},
		{time = 109.9, text = "Battlecry"},
		{time = 113.4, text = "Can you feel it taking over?"},
		{time = 116.0, text = "Can you feel it taking over?"},
		{time = 120.5, text = "Battlecry"},
		{time = 124.1, text = "Can you feel it taking over?"},
		{time = 126.6, text = "Can you feel it taking over?"},
		{time = 153.6, text = "Can you hear the sirens?"},
		{time = 156.4, text = "Can you see the enemy line?"},
		{time = 159.0, text = "I feel it coming closer"},
		{time = 164.1, text = "We're braver than a lion"},
		{time = 166.9, text = "We're steady in our state of mind"},
		{time = 169.7, text = "Keeping out composure"},
	},
}