-- TODO create helper functions to repeat certain sections
GM.ZELyrics = {
	["ffvii_out_of_hell.mp3"] = {
		-- intro
		{time = 12.9, text = "Oh, oh, oh"},
		{time = 14.9, text = "Oh, oh"},
		{time = 16, text = "Oh, oh, oh"},
		{time = 18, text = "Oh, oh"},
		-- verse 1
		{time = 18.8, text = "I've been down in the dirt, lost for so long"},
		{time = 22.2, text = "And pushed around, beaten down"},
		{time = 25.2, text = "Got nothing left to lose, all hope is gone"},
		{time = 28.5, text = "Got buried deep underground"},
		-- prechorus
		{time = 31.8, text = "Oh, can you see me?"},
		{time = 38.1, text = "Oh, can you hear me?"},
		-- chorus
		{time = 41.8, text = "Can you hear me screaming for you?"},
		{time = 44.8, text = "I'm afraid I'm gonna die down here"},
		{time = 47.8, text = "I can't save, I can't save myself"},
		{time = 51.2, text = "Get me out, get me out of Hell"},
		{time = 54.1, text = "I'm suffocating waiting for you"},
		{time = 57.4, text = "Cause the angels don't fly down here"},
		{time = 60.4, text = "I need you because no one else"},
		{time = 63.5, text = "Can get me out, get me out of Hell?"},
		-- verse 2
		{time = 72.5, text = "I can't trust anyone, all that I got"},
		{time = 75.7, text = "Is another scarred, broken heart"},
		{time = 78.8, text = "I've been stabbed in the back, the bleeding won't stop"},
		{time = 82, text = "Just another cut in the dark"},
		-- prechorus
		{time = 85.5, text = "Oh, can you see me?"},
		{time = 91.8, text = "Oh, can you hear me?"},
		-- chorus
		{time = 95.3, text = "Can you hear me screaming for you?"},
		{time = 98.5, text = "I'm afraid I'm gonna die down here"},
		{time = 101.4, text = "I can't save, I can't save myself"},
		{time = 104.8, text = "Get me out, get me out of Hell"},
		{time = 107.8, text = "I'm suffocating waiting for you"},
		{time = 111.1, text = "Cause the angels don't fly down here"},
		{time = 114.1, text = "I need you because no one else"},
		{time = 117.2, text = "Can get me out, get me out of Hell?"},
		-- chorus
		{time = 145.8, text = "Can you hear me screaming for you?"},
		{time = 149, text = "I'm afraid I'm gonna die down here"},
		{time = 152, text = "I can't save, I can't save myself"},
		{time = 155.4, text = "Get me out, get me out of Hell"},
		{time = 158.3, text = "I'm suffocating waiting for you"},
		{time = 161.7, text = "Cause the angels don't fly down here"},
		{time = 164.7, text = "I need you because no one else"},
		{time = 167.8, text = "Can get me out, get me out of Hell?"},
		-- outro
		{time = 171.5, text = "Can you hear me?"},
		{time = 174.7, text = "Can you see me?"},
		{time = 177.8, text = "I can feel you now"},
		{time = 180.6, text = "Get me out, get me out of Hell"},
		{time = 183.8, text = "Can you hear me screaming for you?"},
		{time = 187, text = "I'm afraid I'm gonna die down here"},
		{time = 190, text = "I need you because no one else"},
		{time = 193, text = "Can get me out, get me out of Hell?"},
	},
	["ffvii_propane_nightmares.mp3"] = {
		-- intro
		{time = 2.1, text = "In a trail of fire I know we will be free again"},
		{time = 7.5, text = "In the end we will be one"},
		{time = 13, text = "In a trail of fire I'll burn before you bury me"},
		{time = 18.4, text = "Set your sights for the sun"},

		{time = 46.1, text = "Mind is willing, soul remains"},
		{time = 49, text = "This woman cannot be saved"},
		{time = 51.6, text = "From the draw into the fire"},

		{time = 57, text = "Mind is willing, soul remains"},
		{time = 59.9, text = "This woman cannot be saved"},
		{time = 62.7, text = "From the draw into the fire"},

		{time = 65.5, text = "Anything to bring it on home"},
		{time = 72.3, text = "Bring it on home"},
		{time = 77.9, text = "Bring it on home"},
		{time = 83.4, text = "Bring it on home"},

		{time = 112.3, text = "Much to weak to jump yourself"},
		{time = 115.1, text = "Heal the wounds or crack the shell"},
		{time = 117.9, text = "Lift yourself from once below"},

		{time = 123.3, text = "Much to weak to jump yourself"},
		{time = 126.1, text = "Heal the wounds or crack the shell"},
		{time = 128.9, text = "Lift yourself from once below"},

		{time = 131.7, text = "Praise the anger bring it on home"},
	},
	["ffvii_granitev2.mp3"] = {
		{time = 42.4, text = "You can hide your eyes"},
		{time = 43.9, text = "You can dim the lights"},
		{time = 45.2, text = "But they are watching"},
		{time = 47.5, text = "This is a new time with a different kind"},
		{time = 50.7, text = "They are the future"},
		{time = 53, text = "The only one"},
		{time = 59, text = "It's a final call for the setting sun when they get closer"},
		{time = 64.3, text = "And with a fall from grace thy will be done, the show is over"},
		{time = 69.2, text = "It's a new dawn"},
		{time = 86.8, text = "Just leave this place behind"},
		{time = 89.4, text = "I'll clear your bloodshot mind"},
		{time = 92, text = "They only wanted your life on demand"},
		{time = 96.9, text = "This is a better way"},
		{time = 119.7, text = "They were standing by, no time to hide, no meeting halfway"},
		{time = 125.1, text = "You were sucking life through the needle's eye, this is a new day"},
		{time = 130, text = "And they have won"},
		{time = 135.9, text = "We will surrender now or be outdone, left in the open"},
		{time = 141.9, text = "It's the cooling of the horizon, they are the future"},
		{time = 146.7, text = "The future"},
		{time = 169.3, text = "When all your fears combined"},
		{time = 171.8, text = "The manifest was refined"},
		{time = 174.7, text = "I know you really tried to understand"},
		{time = 179.6, text = "This is a new way"}
	},
	["ffvii_rise.mp3"] = {
		{time = 23.8, text = "All I see is shattered pieces"},
		{time = 26.5, text = "I can't keep it hidden like a secret"},
		{time = 29, text = "I can't look away"},
		{time = 31.4, text = "From all this pain in a world we made"},
		{time = 34.5, text = "Everyday you need"},
		{time = 35.7, text = "A bulletproof vest"},
		{time = 37.3, text = "To save yourself from what you could never guess!"},
		{time = 39.9, text = "Am I safe today?"},
		{time = 42.2, text = "When I step outside in the wars we wage!"},
		{time = 45.5, text = "Our future's here and now"},
		{time = 48.6, text = "Here comes the countdown"},
		{time = 51.5, text = "Sound it off, this is the call"},
		{time = 55, text = "Rise in revolution"},
		{time = 57.6, text = "It's our time to change it all"},
		{time = 60.3, text = "Rise and revolution"},
		{time = 53.3, text = "Unite and fight to make a better life"},
		{time = 68.3, text = "Everybody one for all"},
		{time = 71, text = "Sound off, this is the call"},
		{time = 74.2, text = "Tonight, we rise"},
		{time = 76.5, text = "(Rise)"},
		{time = 79.6, text = "Tonight, we rise"},
		{time = 82.4, text = "(Rise)"},
		{time = 85.3, text = "Tonight, we rise"},
		{time = 88.1, text = "(Rise, rise)"},
		{time = 90.3, text = "Like a hand grenade"},
		{time = 91.7, text = "Thrown in a hurricane"},
		{time = 93.1, text = "Spinning in chaos"},
		{time = 94.3, text = "Trying to escape the flame"},
		{time = 95.6, text = "Yesterday is gone"},
		{time = 98.5, text = "Faster than the blast of a car bomb"},
		{time = 101.4, text = "And when the scars heal"},
		{time = 102.7, text = "The pain passes"},
		{time = 103.9, text = "As hope burns, we rise from the ashes"},
		{time = 106.6, text = "Darkness fades away"},
		{time = 109.1, text = "And the light shines on a brave new day"},
		{time = 112.4, text = "Our future's here and now"},
		{time = 115, text = "Here comes the countdown"},
		{time = 118.5, text = "Sound it off, this is the call"},
		{time = 121.5, text = "Rise in revolution"},
		{time = 124.5, text = "It's our time to change it all"},
		{time = 127.2, text = "Rise in revolution"},
		{time = 130.4, text = "Unite and fight to make a better life"},
		{time = 135.3, text = "Everybody one for all"},
		{time = 137.7, text = "Sound off, this is the call"},
		{time = 141, text = "Tonight, we rise"},
		{time = 143.6, text = "(Rise)"},
		{time = 146.3, text = "Tonight, we rise"},
		{time = 148.9, text = "(Rise)"},
		{time = 151.9, text = "Tonight, we rise!"},
		{time = 154.6, text = "In a world gone mad"}
		-- this file has more but due to the time between the trigger start and the next music trigger it doesnt usually go past this, i'll update in future if i ever see it somehow get this far
	},
}
