GM.ZELyrics = {
	["e_stage_5_start.mp3"] = {
		{time = 23, text = "Your last chance"},
		{time = 26, text = "Last summer"},
		{time = 29, text = "Your last dance"},
		{time = 31, text = "To beat to your own drummer"},
		{time = 35, text = "Go out fighting"},
		{time = 37, text = "Go out young"},
		{time = 40, text = "A flash of lightning"},
		{time = 43, text = "Eclipse the sun"},
		{time = 45, text = "Your last chance"},
		{time = 49, text = "Last summer"},
		{time = 51, text = "Your last dance"},
		{time = 54, text = "To beat to your own drummer"},
		{time = 57, text = "Go out fighting"},
		{time = 60, text = "Go out young"},
		{time = 62, text = "A flash of lightning"},
		{time = 65, text = "Eclipse the sun"},
		{time = 67, text = "Brace yourself brace yourself"},
		{time = 87, text = "Brace yourself for the grand finale"},
		{time = 91, text = "Whoa oh~~~"},
		{time = 131, text = "Brace yourself for the grand finale"},
		{time = 156, text = "Your last chance"},
		{time = 159, text = "Last summer"},
		{time = 162, text = "Your last dance"},
		{time = 164, text = "To beat to your own drummer"},
		{time = 168, text = "Go out fighting"},
		{time = 171, text = "Go out young"},
		{time = 173, text = "A flash of lightning"},
		{time = 176, text = "Eclipse the sun"},
		{time = 178, text = "Brace yourself brace yourself"},
		{time = 198, text = "Brace yourself for the grand finale"},
		{time = 202, text = "Whoah oh~~~"},
		{time = 242, text = "Brace yourself for the grand finale"},
	},
	["e_stage_5_top.mp3"] = {
		{time = 6, text = "It's in your eyes, a color fade-out"},
		{time = 12, text = "Looks like a new transition"},
		{time = 17, text = "Is starting up and shaking your ground"},
		{time = 22, text = "Turning your head to see a new day calling"},
		{time = 29, text = "Does it feel like a head to lean on"},
		{time = 35, text = "A snapshot from where you were born"},
		{time = 40, text = "I'm looking for your hand in the rought"},
		{time = 44, text = "You're caught in the wire"},
		{time = 47, text = "Well I'll life you out"},
		{time = 51, text = "When I'm falling down"},
		{time = 56, text = "Will you pick me up again"},
		{time = 62, text = "When I'm too far gone"},
		{time = 67, text = "Dead in the eys of my friends"},
		{time = 73, text = "Will you take me out of here"},
		{time = 75, text = "When I'm staring down the barrel"},
		{time = 78, text = "When I'm blinded by the lights"},
		{time = 81, text = "When I cannot see your face"},
		{time = 84, text = "Take me out of here"},
		{time = 87, text = "Take me out of here"},
		{time = 90, text = "Take me out of here"},
		{time = 93, text = "Take me ouf ot here"},
		{time = 94, text = "Leaning on the action"},
		{time = 97, text = "Caught in a cellphone's rays"},
		{time = 99, text = "Bleeding on the sofa"},
		{time = 102, text = "Staring at the wayside"},
		{time = 104, text = "He's coming and she knows it"},
		{time = 108, text = "Even if she knows why"},
		{time = 110, text = "Footsetps in the hallway"},
		{time = 113, text = "Girl you haven't got time"},
		{time = 115, text = "All I believe"},
		{time = 118, text = "And all I've known"},
		{time = 120, text = "Are being taken from me"},
		{time = 124, text = "Can't get home"},
		{time = 126, text = "Led to a world"},
		{time = 129, text = "When worlds collide"},
		{time = 132, text = "Let the fear collapse bring no surprise"},
		{time = 137, text = "Take me out of here"},
		{time = 159, text = "Feed the fire, break your vision"},
		{time = 162, text = "Throw your fists up come on with me"},
	},
	["e_stage_4_end.mp3"] = {
		{time = 2.5, text = "Like memories in cold decay"},
		{time = 5, text = "Transmissions echoing away"},
		{time = 7.5, text = "Far from the world of you and I"},
		{time = 11, text = "Where oceans bleed into the sky"},
		{time = 41, text = "God save us everyone"},
		{time = 43, text = "Will we burn inside the fires of a thousand suns"},
		{time = 46, text = "For ther sins of our hands"},
		{time = 47, text = "The sins of our tongue"},
		{time = 48, text = "The sins of our fathers"},
		{time = 49, text = "The sins of our young"},
		{time = 51, text = "No"},
		{time = 52, text = "God save us everyone"},
		{time = 54, text = "Will we burn inside the fires of a thousand suns"},
		{time = 57, text = "For the sins of our hands"},
		{time = 58, text = "The sins of our tongue"},
		{time = 59, text = "The sins of our fathers"},
		{time = 61, text = "The sins of our young"},
		{time = 63, text = "No"},
		{time = 64, text = "And when I close my eyes tonight"},
		{time = 66, text = "To sympphonies of blinding light"},
		{time = 74.5, text = "Like memories in cold decay"},
		{time = 77, text = "Transmissions echoing away"},
		{time = 80, text = "Far from the world of you and I"},
		{time = 83, text = "Where oceans bleed into the sky"},
		{time = 107, text = "Like memories in cold decay"},
		{time = 110, text = "Transmissions echoin away"},
		{time = 113, text = "Far from the world of you and I"},
		{time = 116, text = "Where oceans bleed into the sky"},
		{time = 130.5, text = "Lift me up! Let me go!"},
	},
	["e_stage_3_boss.mp3"] = {
		{time = 66, text = "If I struggle a lifetime"},
		{time = 69, text = "What would my body be?"},
		{time = 72, text = "An empty shell"},
		{time = 74, text = "On which a demon fed"},

		{time = 77, text = "Could be a heavy burden"},
		{time = 79, text = "To stay true to your words"},
		{time = 83, text = "Speak up"},
		{time = 85, text = "I wanna silence everything"},

		{time = 89, text = "If I got no plan"},
		{time = 94, text = "Doesn't mean that I get what I want for free"},
		{time = 100, text = "If I got no meaning"},
		{time = 105, text = "Would you force me to a place where I make sense?"},
		{time = 110, text = "Cause nothing lasts forever...!"},

		{time = 115, text = "How do I get home?"},
		{time = 118, text = "Everything revolves around me"},
		{time = 120, text = "If I can't find myself?"},
		{time = 123, text = "It's so completely fake"},

		{time = 126, text = "How do I get home?"},
		{time = 129, text = "Everything revolves around me"},
		{time = 131, text = "If even you can't help"},
		{time = 136, text = "Dark nights on my soul"},

		{time = 161, text = "I deny failure"},
		{time = 163, text = "I ignite"},
		{time = 165, text = "Woe is on my misery"},
		{time = 168, text = "She wins all their eyes"},

		{time = 170, text = "Realize what defies our fate"},
		{time = 173, text = "This is not me, this is me"},
		{time = 176, text = "So if I struggle a lifetime"},
		{time = 179, text = "What good would that do?"},

		{time = 182, text = "If I got a plan"},
		{time = 188, text = "Doesn't have to stop the feeling inside"},
		{time = 193, text = "If I do make sense"},
		{time = 199, text = "Would you drag me down?"},
		{time = 203, text = "'Cause nothing lasts forever"},

		{time = 231, text = "How do I get home?"},
		{time = 234, text = "Everything revolves around me"},
		{time = 236, text = "If I can't find myself?"},
		{time = 240, text = "It's so completely fake"},

		{time = 242, text = "How do I get home?"},
		{time = 245, text = "Everything revolves around me"},
		{time = 247, text = "If even you can't help"},
		{time = 251, text = "Dark nights on my soul"},
	},
	["e_stage_5_end_bad.mp3"] = {
		{time = .7, text = "For everything that could have been"},
		{time = 6.5, text = "Well, at least we took the ride"},
		{time = 12.1, text = "There's no relief in bitterness"},
		{time = 17.4, text = "Might as well let it die"},
	},
	["e_stage_5_end_good_1.mp3" ] = {
		{time = .3, text = "Come on down to the other side"},
		{time = 3.5, text = "Come with us through the gates of hell"},
		{time = 6.9, text = "We will drag you from where you are"},
		{time = 10.6, text = "To where you belong"},
		{time = 14, text = "Come on down to the other side"},
		{time = 17.2, text = "Come with us through the gates of hell"},
		{time = 20.8, text = "We will drag you from where you are"},
		{time = 24.5, text = "To where you belong"},
		{time = 28.7, text = "We are in your spirit"},
		{time = 32.1, text = "We're everywhere you turn"},
		{time = 35.2, text = "From the cover to the cover"},
		{time = 37.3, text = "The cover to the cover"},
		{time = 39, text = "Your lover (to your brother)"},
		{time = 40.5, text = "To your mother (the others)"},
		{time = 42.6, text = "You, you are so precious (precious)"},
		{time = 46.3, text = "But now you've gone away"},
		{time = 49, text = "And I am falling apart"},
		{time = 51.8, text = "Under the waves"},
		{time = 53.9, text = "(The waves, the waves, the waves...)"}
	},
	["e_stage_5_end_good_2_extra.mp3"] = {
		{time = .6, text = "Down to the other side"},
		{time = 3.5, text = "Come with us through the gates of hell"},
		{time = 6.9, text = "We will drag you from where you are"},
		{time = 10.7, text = "To where you belong"},
		{time = 14.1, text = "Come on down to the other side"},
		{time = 17.4, text = "Come with us through the gates of hell"},
		{time = 20.7, text = "We will drag you from where you are"},
		{time = 24.6, text = "To where you belong"}
	},
}