GM.ZELyrics = {
	["e_stage_5_start.mp3"] = {
		{time = 23.00, text = "Your last chance"},
		{time = 26.00, text = "Last summer"},
		{time = 29.00, text = "Your last dance"},
		{time = 31.00, text = "To beat to your own drummer"},
		{time = 35.00, text = "Go out fighting"},
		{time = 37.00, text = "Go out young"},
		{time = 40.00, text = "A flash of lightning"},
		{time = 43.00, text = "Eclipse the sun"},
		{time = 45.00, text = "Your last chance"},
		{time = 49.00, text = "Last summer"},
		{time = 51.00, text = "Your last dance"},
		{time = 54.00, text = "To beat to your own drummer"},
		{time = 57.00, text = "Go out fighting"},
		{time = 60.00, text = "Go out young"},
		{time = 62.00, text = "A flash of lightning"},
		{time = 65.00, text = "Eclipse the sun"},
		{time = 67.00, text = "Brace yourself brace yourself"},
		{time = 87.00, text = "Brace yourself for the grand finale"},
		{time = 91.00, text = "Whoa oh~~~"},
		{time = 131.00, text = "Brace yourself for the grand finale"},
		{time = 156.00, text = "Your last chance"},
		{time = 159.00, text = "Last summer"},
		{time = 162.00, text = "Your last dance"},
		{time = 164.00, text = "To beat to your own drummer"},
		{time = 168.00, text = "Go out fighting"},
		{time = 171.00, text = "Go out young"},
		{time = 173.00, text = "A flash of lightning"},
		{time = 176.00, text = "Eclipse the sun"},
		{time = 178.00, text = "Brace yourself brace yourself"},
		{time = 198.00, text = "Brace yourself for the grand finale"},
		{time = 202.00, text = "Whoah oh~~~"},
		{time = 242.00, text = "Brace yourself for the grand finale"},
	},
	["e_stage_5_top.mp3"] = {
		{time = 6.00, text = "It's in your eyes, a color fade-out"},
		{time = 12.00, text = "Looks like a new transition"},
		{time = 17.00, text = "Is starting up and shaking your ground"},
		{time = 22.00, text = "Turning your head to see a new day calling"},
		{time = 29.50, text = "Does it feel like a head to lean on"},
		{time = 35.00, text = "A snapshot from where you were born"},
		{time = 40.00, text = "I'm looking for your hand in the rought"},
		{time = 44.00, text = "You're caught in the wire"},
		{time = 47.00, text = "Well I'll life you out"},
		{time = 51.00, text = "When I'm falling down"},
		{time = 56.00, text = "Will you pick me up again"},
		{time = 62.00, text = "When I'm too far gone"},
		{time = 67.00, text = "Dead in the eys of my friends"},
		{time = 73.00, text = "Will you take me out of here"},
		{time = 75.00, text = "When I'm staring down the barrel"},
		{time = 78.00, text = "When I'm blinded by the lights"},
		{time = 81.00, text = "When I cannot see your face"},
		{time = 84.00, text = "Take me out of here"},
		{time = 87.00, text = "Take me out of here"},
		{time = 90.00, text = "Take me out of here"},
		{time = 93.00, text = "Take me ouf ot here"},
		{time = 94.00, text = "Leaning on the action"},
		{time = 97.00, text = "Caught in a cellphone's rays"},
		{time = 99.00, text = "Bleeding on the sofa"},
		{time = 102.00, text = "Staring at the wayside"},
		{time = 104.00, text = "He's coming and she knows it"},
		{time = 108.00, text = "Even if she knows why"},
		{time = 110.00, text = "Footsetps in the hallway"},
		{time = 113.00, text = "Girl you haven't got time"},
		{time = 115.00, text = "All I believe"},
		{time = 118.00, text = "And all I've known"},
		{time = 120.00, text = "Are being taken from me"},
		{time = 124.00, text = "Can't get home"},
		{time = 126.00, text = "Led to a world"},
		{time = 129.00, text = "When worlds collide"},
		{time = 132.00, text = "Let the fear collapse bring no surprise"},
		{time = 137.00, text = "Take me out of here"},
		{time = 159.00, text = "Feed the fire, break your vision"},
		{time = 162.00, text = "Throw your fists up come on with me"},
	},
	["e_stage_4_end.mp3"] = {
		{time = 2.50, text = "Like memories in cold decay"},
		{time = 5.00, text = "Transmissions echoing away"},
		{time = 7.50, text = "Far from the world of you and I"},
		{time = 11.00, text = "Where oceans bleed into the sky"},
		{time = 41.00, text = "God save us everyone"},
		{time = 43.00, text = "Will we burn inside the fires of a thousand suns"},
		{time = 46.00, text = "For ther sins of our hands"},
		{time = 47.00, text = "The sins of our tongue"},
		{time = 48.00, text = "The sins of our fathers"},
		{time = 49.00, text = "The sins of our young"},
		{time = 51.00, text = "No"},
		{time = 52.00, text = "God save us everyone"},
		{time = 54.00, text = "Will we burn inside the fires of a thousand suns"},
		{time = 57.00, text = "For the sins of our hands"},
		{time = 58.00, text = "The sins of our tongue"},
		{time = 59.00, text = "The sins of our fathers"},
		{time = 61.00, text = "The sins of our young"},
		{time = 63.00, text = "No"},
		{time = 64.00, text = "And when I close my eyes tonight"},
		{time = 66.00, text = "To sympphonies of blinding light"},
		{time = 74.50, text = "Like memories in cold decay"},
		{time = 77.00, text = "Transmissions echoing away"},
		{time = 80.00, text = "Far from the world of you and I"},
		{time = 83.00, text = "Where oceans bleed into the sky"},
		{time = 107.00, text = "Like memories in cold decay"},
		{time = 110.00, text = "Transmissions echoin away"},
		{time = 113.00, text = "Far from the world of you and I"},
		{time = 116.00, text = "Where oceans bleed into the sky"},
		{time = 130.50, text = "Lift me up! Let me go!"},
	},
	["e_stage_3_boss.mp3"] = {
		{time = 66.00, text = "If I struggle a lifetime"},
		{time = 69.00, text = "What would my body be?"},
		{time = 72.00, text = "An empty shell"},
		{time = 74.00, text = "On which a demon fed"},

		{time = 77.00, text = "Could be a heavy burden"},
		{time = 79.00, text = "To stay true to your words"},
		{time = 83.00, text = "Speak up"},
		{time = 85.00, text = "I wanna silence everything"},

		{time = 89.00, text = "If I got no plan"},
		{time = 94.00, text = "Doesn't mean that I get what I want for free"},
		{time = 100.00, text = "If I got no meaning"},
		{time = 105.00, text = "Would you force me to a place where I make sense?"},
		{time = 110.00, text = "Cause nothing lasts forever...!"},

		{time = 115.00, text = "How do I get home?"},
		{time = 118.00, text = "Everything revolves around me"},
		{time = 120.00, text = "If I can't find myself?"},
		{time = 123.00, text = "It's so completely fake"},

		{time = 126.00, text = "How do I get home?"},
		{time = 129.00, text = "Everything revolves around me"},
		{time = 131.00, text = "If even you can't help"},
		{time = 136.00, text = "Dark nights on my soul"},

		{time = 161.00, text = "I deny failure"},
		{time = 163.00, text = "I ignite"},
		{time = 165.00, text = "Woe is on my misery"},
		{time = 168.00, text = "She wins all their eyes"},

		{time = 170.00, text = "Realize what defies our fate"},
		{time = 173.00, text = "This is not me, this is me"},
		{time = 176.00, text = "So if I struggle a lifetime"},
		{time = 179.00, text = "What good would that do?"},

		{time = 182.00, text = "If I got a plan"},
		{time = 188.00, text = "Doesn't have to stop the feeling inside"},
		{time = 193.00, text = "If I do make sense"},
		{time = 199.00, text = "Would you drag me down?"},
		{time = 203.00, text = "'Cause nothing lasts forever"},

		{time = 231.00, text = "How do I get home?"},
		{time = 234.00, text = "Everything revolves around me"},
		{time = 236.00, text = "If I can't find myself?"},
		{time = 240.00, text = "It's so completely fake"},

		{time = 242.00, text = "How do I get home?"},
		{time = 245.00, text = "Everything revolves around me"},
		{time = 247.00, text = "If even you can't help"},
		{time = 251.00, text = "Dark nights on my soul"},
	},
	["e_stage_5_end_bad.mp3"] = {
		{time = .7, text = "For everything that could have been"},
		{time = 6.5, text = "Well, at least we took the ride"},
		{time = 12.1, text = "There's no relief in bitterness"},
		{time = 17.4, text = "Might as well let it die"},
	},
	["e_stage_5_end_good_1.mp3" ] = {
		{time = .3, text = "Come on down to the other side"},
		{time = 3.5, text = "Come with us through the gates of hell"},
		{time = 6.9, text = "We will drag you from where you are"},
		{time = 10.6, text = "To where you belong"},
		{time = 14, text = "Come on down to the other side"},
		{time = 17.2, text = "Come with us through the gates of hell"},
		{time = 20.8, text = "We will drag you from where you are"},
		{time = 24.5, text = "To where you belong"},
		{time = 28.7, text = "We are in your spirit"},
		{time = 32.1, text = "We're everywhere you turn"},
		{time = 35.2, text = "From the cover to the cover"},
		{time = 37.3, text = "The cover to the cover"},
		{time = 39, text = "Your lover (to your brother)"},
		{time = 40.5, text = "To your mother (the others)"},
		{time = 42.6, text = "You, you are so precious (precious)"},
		{time = 46.3, text = "But now you've gone away"},
		{time = 49, text = "And I am falling apart"},
		{time = 51.8, text = "Under the waves"},
		{time = 53.9, text = "(The waves, the waves, the waves...)"}
	},
	["e_stage_5_end_good_2_extra.mp3"] = {
		{time = .6, text = "Down to the other side"},
		{time = 3.5, text = "Come with us through the gates of hell"},
		{time = 6.9, text = "We will drag you from where you are"},
		{time = 10.7, text = "To where you belong"},
		{time = 14.1, text = "Come on down to the other side"},
		{time = 17.4, text = "Come with us through the gates of hell"},
		{time = 20.7, text = "We will drag you from where you are"},
		{time = 24.6, text = "To where you belong"}
	},
}