GM.ZELyrics = {
    ["zm_round1.mp3"] = {
        {time = 41.01, text = "When this began"},
        {time = 42.35, text = "I had nothing to say"},
        {time = 44.02, text = "And I'd get lost in the nothingness inside of me"},
        {time = 46.82, text = "I was confused"},
        {time = 47.71, text = "And I let it all out to find"},
        {time = 49.74, text = "That I'm not the only person with these things in mind"},
        {time = 52.59, text = "Inside of me"},
        {time = 53.4, text = "But all that they can see the words revealed"},
        {time = 55.61, text = "Is the only real thing that I've got left to feel"},
        {time = 58.54, text = "Nothing to lose"},
        {time = 59.41, text = "Just stuck: hollow and alone"},
        {time = 61.59, text = "And the fault is my own"},
        {time = 63.02, text = "And the fault is my own"},
        {time = 64.57, text = "I wanna heal: I wanna feel"},
        {time = 67.35, text = "What I thought was never real"},
        {time = 70.24, text = "I wanna let go of the pain I felt so long"},
        {time = 74.49, text = "Erase all the pain till it's gone"},
        {time = 76.25, text = "I wanna heal: I wanna feel"},
        {time = 79.18, text = "Like I'm close to something real"},
        {time = 82.09, text = "I wanna find something I wanted all along"},
        {time = 87.01, text = "Somewhere I belong"},
        {time = 89.8, text = "And I've got nothing to say"},
        {time = 91.18, text = "I can't believe I didn't fall right down on my face"},
        {time = 93.95, text = "I was confused"},
        {time = 94.92, text = "Looking everywhere only to find"},
        {time = 96.92, text = "That it's not the way I had imagined it all in my mind"},
        {time = 99.76, text = "So what am I?"},
        {time = 100.69, text = "What do I have but negativity?"},
        {time = 102.72, text = "Cause I can't justify the way everyone is looking at me"},
        {time = 105.71, text = "Nothing to lose"},
        {time = 106.55, text = "Nothing to gain: hollow and alone"},
        {time = 108.69, text = "And the fault is my own"},
        {time = 110.12, text = "And the fault is my own"},
        {time = 111.7, text = "I wanna heal: I wanna feel"},
        {time = 114.69, text = "What I thought was never real"},
        {time = 117.44, text = "I wanna let go of the pain I felt so long"},
        {time = 121.74, text = "Erase all the pain till it's gone"},
        {time = 123.47, text = "I wanna heal: I wanna feel"},
        {time = 126.36, text = "Like I'm close to something real"},
        {time = 129.29, text = "I wanna find something I wanted all along"},
        {time = 134.18, text = "Somewhere I belong"},
        {time = 136.71, text = "I will never know myself"},
        {time = 139.04, text = "Until I do this on my own"},
        {time = 142.32, text = "And I will never feel"},
        {time = 144.99, text = "Anything else until my wounds are healed"},
        {time = 148.22, text = "I will never be"},
        {time = 151.35, text = "Anything till I break away from me"},
        {time = 154.24, text = "I will break away"},
        {time = 156.27, text = "I'll find myself today"},
        {time = 164.03, text = "I wanna heal: I wanna feel"},
        {time = 167.85, text = "What I thought was never real"},
        {time = 170.58, text = "I wanna let go of the pain I felt so long"},
        {time = 174.9, text = "Erase all the pain till it's gone"},
        {time = 176.5, text = "I wanna heal: I wanna feel"},
        {time = 179.5, text = "Like I'm close to something real"},
        {time = 182.36, text = "I wanna find something I wanted all along"},
        {time = 187.21, text = "Somewhere I belong"},
        {time = 190.3, text = "I wanna heal: I wanna feel like I'm"},
        {time = 193.54, text = "Somewhere I belong"},
        {time = 196.25, text = "I wanna heal: I wanna feel like I'm"},
        {time = 199.37, text = "Somewhere I belong"},
        {time = 205.5, text = "Somewhere I belong"},
    },
    ["zm_round2.mp3"] = {
        {time = 0.17, text = "It kills me not to know this but I've all but just forgotten"},
        {time = 4.52, text = "What the color of her eyes were and her scars or how she got them"},
        {time = 10.1, text = "As the telling signs of age rain down a single tear is dropping"},
        {time = 15.28, text = "Through the valleys of an aging face that this world has forgotten"},
        {time = 38.8, text = "There is no reconciliation that will put me in my place"},
        {time = 43.13, text = "And there is no time like the present to drink these draining seconds"},
        {time = 48.3, text = "But seldom do these words ring true when I'm constantly failing you"},
        {time = 51.84, text = "Like walls that we just can't break through until we disappear"},
        {time = 55.79, text = "So tell me now"},
        {time = 57.64, text = "If this ain't love then how do we get out?"},
        {time = 61.85, text = "Because I don't know"},
        {time = 63.2, text = "That's when she said I don't hate you boy"},
        {time = 65.95, text = "I just want to save you while there's still something left to save"},
        {time = 71.77, text = "That's when I told her I love you girl"},
        {time = 74.48, text = "But I'm not the answer to the questions that you still have"},
        {time = 90.62, text = "But the day pressed on like crushing weights"},
        {time = 92.61, text = "For no man does it ever wait"},
        {time = 94.75, text = "Like memories of dying days"},
        {time = 96.81, text = "That deafen us like hurricanes"},
        {time = 99.31, text = "Bathed in flames we held the brand"},
        {time = 101.41, text = "Uncurled the fingers in your hand"},
        {time = 103.41, text = "Pressed into the flesh like sand"},
        {time = 105.41, text = "Now do you understand?"},
        {time = 107.4, text = "So tell me now"},
        {time = 108.86, text = "If this ain't love then how do we get out?"},
        {time = 112.96, text = "Because I don't know"},
        {time = 114.41, text = "That's when she said I don't hate you boy"},
        {time = 117.16, text = "I just want to save you while there's still something left to save"},
        {time = 123.46, text = "That's when I told her I love you girl"},
        {time = 125.51, text = "But I'm not the answer to the questions that you still have"},
        {time = 147.6, text = "1000 miles away"},
        {time = 149.56, text = "There's nothing left to say"},
        {time = 151.77, text = "But so much left that I don't know"},
        {time = 155.68, text = "We never had a choice"},
        {time = 158.24, text = "This world is too much noise"},
        {time = 160.34, text = "It takes me under"},
        {time = 162.51, text = "It takes me under once again"},
        {time = 175.94, text = "I don't hate you"},
        {time = 181.96, text = "I don't hate you: no"},
        {time = 188.28, text = "So tell me now"},
        {time = 190.79, text = "If this ain't love then how do we get out?"},
        {time = 197.35, text = "Because I don't know"},
        {time = 199.36, text = "That's when she said I don't hate you boy"},
        {time = 201.71, text = "I just want to save you while there's still something left to save"},
        {time = 208.15, text = "That's when I told her I love you girl"},
        {time = 210.36, text = "But I'm not the answer to the questions that you still have"},
        {time = 217.77, text = "I don't hate you"},
        {time = 221.68, text = "I don't hate you"},
        {time = 225.77, text = "I don't hate you"},
    },
    ["zm_round3.mp3"] = {
        {time = 23.83, text = "Do you spend your days counting the hours you're awake"},
        {time = 28.0, text = "And when night covers the sky you find yourself doing the same"},
        {time = 32.81, text = "It's a burden you've been buried"},
        {time = 35.05, text = "In spite of all your prayers"},
        {time = 37.3, text = "There's a light turned off inside your heart"},
        {time = 39.74, text = "And you don't remember what it's like to care"},
        {time = 42.77, text = "Knees are weak hands are shaking I can't breathe"},
        {time = 45.97, text = "So give me the drug"},
        {time = 47.33, text = "Keep me alive"},
        {time = 48.44, text = "Give me what's left of my life"},
        {time = 50.52, text = "But let me go"},
        {time = 55.29, text = "Pull this plug"},
        {time = 56.43, text = "Let me breathe"},
        {time = 57.61, text = "On my own I'm finally free"},
        {time = 59.87, text = "Don't let me go"},
        {time = 68.86, text = "The trail of crumbs you left"},
        {time = 71.29, text = "somehow got lost along the way"},
        {time = 74.04, text = "If you never meant to leave"},
        {time = 75.98, text = "Then you only had to stay"},
        {time = 78.58, text = "But the memories that haunt us"},
        {time = 80.63, text = "Are cherished just the same"},
        {time = 82.96, text = "As the ones that bring us closer to the sky"},
        {time = 86.48, text = "No matter how grave yet I fall through these clouds reaching are screaming"},
        {time = 92.01, text = "So give me the drug"},
        {time = 93.37, text = "Keep me alive"},
        {time = 94.26, text = "Give me what's left of my life"},
        {time = 96.42, text = "But let me go"},
        {time = 101.22, text = "Pull this plug"},
        {time = 102.25, text = "Let me breathe"},
        {time = 103.41, text = "On my own I'm finally free"},
        {time = 105.78, text = "Don't let me go"},
        {time = 110.97, text = "This grip loosens but it never breaks (never breaks)"},
        {time = 115.42, text = "We carry nothing but again you will forsake"},
        {time = 120.25, text = "You words are always there to break my fall (break my fall)"},
        {time = 124.6, text = "In them I find the comfort"},
        {time = 126.76, text = "to see through it all"},
        {time = 129.3, text = "(Guide me through un-chartered waters)"},
        {time = 133.16, text = "(Before we lose our way again)"},
        {time = 138.17, text = "(Will you be my compass)"},
        {time = 142.29, text = "(Until forever until forever ends)"},
        {time = 147.51, text = "Knees are weak hands are shaking I can't breathe"},
        {time = 150.16, text = "So give me the drug"},
        {time = 151.45, text = "Keep me alive"},
        {time = 152.64, text = "Give me what's left of my life"},
        {time = 154.76, text = "But let me go"},
        {time = 159.58, text = "Pull this plug"},
        {time = 160.64, text = "Let me breathe"},
        {time = 161.65, text = "On my own I'm finally free"},
        {time = 163.97, text = "Don't let me go"},
        {time = 168.85, text = "Don't let me go"},
        {time = 177.45, text = "Don't let me go"},
    },
}
