GM.ZELyrics = {
	["zm_bgm.mp3"] = {
		{time = 17.2, text = "Consentesdei/Juno/Juppiter/Minerva/Apollo/Mars/Ceres"},
		{time = 21.4, text = "Mercurius/Diana/Bacchus/Uto/Vesta/Venus"},
		{time = 26.7, text = "微睡(まどろ)みの淵で目蓋に揺蕩う"},
		{time = 34.8, text = "夢想の神は優雅に微笑み死を降"},
		{time = 38.7, text = "時空を総べる因果の鎖は絡み出"},
		{time = 43.0, text = "神の与えし空想 Program"},
		{time = 52.0, text = "さぁ eins zwei drei! 重なり合"},
		{time = 56.0, text = "さぁ eins zwei drei! 死を躱し"},
		{time = 60.0, text = "消滅の遊戯に焦がれる奇跡を奪う Suvivalgame"},
		{time = 72.7, text = "螺旋のように"},
		{time = 86.1, text = "Consentesdei/Juno/Juppiter/Minerva/Apollo/Mars/Ceres"},
		{time = 90.2, text = "Mercurius/Diana/Bacchus/Uto/Vesta/Venus"},
		{time = 95.9, text = "泡沫の未来書き換えるよう"},
		{time = 103.5, text = "空想繋ぐ輪廻のノイズが鳴り渡"},
		{time = 107.7, text = "時間は歪み因果の旋律は崩れ去"},
		{time = 112.0, text = "神の与えし継承 Program"},
		{time = 121.0, text = "さぁ eins zwei drei! 連なり合"},
		{time = 125.2, text = "さぁ eins zwei drei! 死を振り切っ"},
		{time = 128.9, text = "消滅の遊戯に抗う奇跡に挑む Eraser game"},
		{time = 141.5, text = "夢幻のように"},
		{time = 179.8, text = "神の与えし機械(からくり) Program"},
		{time = 189.2, text = "さぁ eins zwei drei! 重なり合"},
		{time = 193.9, text = "さぁ eins zwei drei! 死を躱し"},
		{time = 197.7, text = "eins zwei drei! 連なり合"},
		{time = 201.8, text = "さぁ eins zwei drei! 死を振り切っ"},
		{time = 206.2, text = "消滅の遊戯に焦がれる奇跡を奪う Suvival game"},
		{time = 218.7, text = "螺旋のように"},
		{time = 223.6, text = "哀憐(あいれん)なる傍観"},
		{time = 225.7, text = "焦がれる生死よりも遠"},
		{time = 227.7, text = "最果てにある箱庭で"},
		{time = 229.3, text = "終わりのない奇跡があると"},
		{time = 232.0, text = "信じてい"},
	},
}