GM.ZELyrics = {
    ["nrk4_music_6.mp3"] = {
        -- checking files compared to ze_potc_v4s_4fix, theyre the same
		{time = 32.2, text = "I was running out in the cold light"},
		{time = 35.7, text = "Wondering where to go"},
		{time = 37.7, text = "To run away without you"},
		{time = 43.2, text = "All my fear is coming home"},
		{time = 46, text = "Handing scripts out for the show"},
		{time = 48.8, text = "You can't be me"},
		{time = 51.4, text = "I will become you, tonight..."},

		{time = 65.3, text = "I was wandering under black skies"},
		{time = 68.7, text = "Clutching at what is mine"},
		{time = 70.9, text = "No control left to lose"},
		{time = 76.4, text = "Well I thought that it wouldn't phase me"},
		{time = 79.5, text = "But I'm hiding like a child"},
		{time = 81.9, text = "I feel so guilty"},
		{time = 84.5, text = "I'll make it up to you, tonight..."},

		{time = 88.2, text = "The creatures I've been dreaming are coming down"},
		{time = 93.4, text = "They're changing my future"},
		{time = 99, text = "Visions I had buried underground"},
		{time = 104.2, text = "Return as abusers"},

		{time = 131.5, text = "I was breaking out of my old skin"},
		{time = 135, text = "Choking upon release"},
		{time = 137, text = "I'm in no state to judge you"},
		{time = 142.5, text = "Scratching itches best left alone"},
		{time = 145.3, text = "Chasing memories I used to own"},
		{time = 148.1, text = "I can't wait"},
		{time = 150.7, text = "Til this is over, tonight..."},

		{time = 154.4, text = "The creatures I've been dreaming are coming down"},
		{time = 159.5, text = "They're changing my future"},
		{time = 165.3, text = "Visions I had buried underground"},
		{time = 170.5, text = "Return as abusers"},
    },
    ["nrk5_music_6.mp3"] = {
        {time = 5.9, text = "I lie still as the water"},
        {time = 8.6, text = "But my visions are broken"},
        {time = 11.5, text = "Head caught in the tide as"},
        {time = 14.3, text = "Cruel as the ocean"},
        {time = 17.2, text = "Dreams are made in the distance"},
        {time = 19.7, text = "I will not be among them"},
        {time = 22.6, text = "The silence is killing me"},
        {time = 25.2, text = "And I can hardly touch the ground"},
        {time = 28.2, text = "(Touch the ground..)", autohold = true},
        {time = 37, text = ""}, -- clear above autohold as it fades, should work? unsure if it does
        {time = 48.9, text = "I am deep in a river"},
        {time = 55, text = "Waves above my head"},
        {time = 60.6, text = "Held with no spirit"},
        {time = 65.2, text = "We descend"},
        {time = 70.6, text = "We reach the end"},
        {time = 126, text = "I am deep in a river"},
        {time = 132.4, text = "Waves above my head"},
        {time = 137.8, text = "Held with no spirit"},
        {time = 142.2, text = "We descend"},
        {time = 147.9, text = "We reach the end"},
        {time = 192.4, text = "I am deep in a river"},
        {time = 198.5, text = "Waves above my head"},
        {time = 204.3, text = "Held with no spirit"},
        {time = 208.6, text = "We descend"},
        {time = 214.1, text = "We reach the end"},
        {time = 230.7, text = "We descend"},
        {time = 236.1, text = "We reach the end"}
    },
}