GM.ZELyrics = {
	["tempestlive.mp3"] = {
		{time = 2.5, text = "Saw you the other day"},
		{time = 7.2, text = "Looking so undermined"},
		{time = 13.5, text = "Acting like it wouldn't happen"},
		{time = 17.5, text = "Making sense of anything that you could find"},
		{time = 22.8, text = "Because it's just about to happen"},
		{time = 27.6, text = "And you'll be there"},
		{time = 33.8, text = "You must have known the storm was coming"},
		{time = 38.5, text = "When the clouds appeared"},

		{time = 55.6, text = "May as well let the rain come down"},
		{time = 61.4, text = "And join the circus of people"},
		{time = 66.8, text = "WHile you're there"},

		{time = 101.0, text = "Something is changing"},
		{time = 103.9, text = "Bruising and aching"},
		{time = 106.1, text = "And I'm trying to find out what it is"},
		{time = 111.8, text = "When I fix her, she's breaking"},
		{time = 114.9, text = "Reason keeps escaping me"},
		{time = 117.5, text = "Protecting and burning like a cyst"},

		{time = 145.2, text = "I know that I can help you"},
		{time = 147.9, text = "I just don't fucking want to"},
		{time = 150.2, text = "And the feeling gets stronger by the day"},
		{time = 156.2, text = "You say that I'm selfish"},
		{time = 158.9, text = "But I don't really need this"},
		{time = 161.3, text = "And I'm just so sick of the chase"},

		{time = 167.9, text = "While you are letting your guard down"},
		{time = 173.1, text = "I will be letting myself go"},
		{time = 178.6, text = "While you keep running your ship aground"},
		{time = 184.2, text = "I will be setting myself alight"},

		{time = 211.5, text = "It's too late, you've dropped the drawbridge"},
		{time = 214.6, text = "You let the vampires in"},
		{time = 217.3, text = "I hope you know now that it's nobody's fault but yours"},

		{time = 222.8, text = "It's too late, you've dropped the drawbridge"},
		{time = 225.7, text = "You let the vampires in"},
		{time = 228.5, text = "I hope you know now that it's nobody's fault but yours"},

		{time = 234.1, text = "While you are letting your guard down"},
		{time = 239.4, text = "I will be letting myself go"},
		{time = 245.1, text = "While you keep running your ship aground"},
		{time = 250.6, text = "I will be setting myself alight"},

		{time = 280.2, text = "(ALRIGHT I NEED YOU TO TAKE A DEEP BREATH)"},
		{time = 283.8, text = "(EVERYONE INSIDE BRIXTON ACADEMY)"},
		{time = 286.2, text = "(COME ON)"},
		{time = 290.5, text = "(ROCK IT UP)"},
		{time = 291.4, text = "(YEAH)"},
		{time = 292.1, text = "(YEAH, YEAH)"},
		{time = 292.8, text = "(YEAH, YEAH, YEAH)"},
		{time = 293.4, text = "(YEAH, YEAH, YEAH, YEAH)"},
		{time = 296.2, text = "(GO!)"},
		{time = 316.2, text = "(READY?)"},
		{time = 326.9, text = "(3...)"},
		{time = 327.6, text = "(3... 2...)"},
		{time = 328.3, text = "(3... 2... 1...)"},
		{time = 328.9, text = "(3... 2... 1... GO)"},
		{time = 329.4, text = "(3... 2... 1... GO GO)"},
		{time = 348.8, text = "(SOMEBODY RAISE THE ROOF)"},
		{time = 350.5, text = "(RAISE THE ROOF)"},
	},
}