GM.ZELyrics = {
	["npst_music_6.mp3"] = {
		{time = 1.0, text = "MUZZ - Children of Hell"},
		{time = 12.5, text = "We're working"},
		{time = 15.2, text = "In shackles again"},
		{time = 17.9, text = "The end of a trend"},
		{time = 20.6, text = "The world descends"},
		{time = 22.8, text = "Until we're nothing"},
		{time = 25.9, text = "But the children of hell"},
		{time = 28.9, text = "The angels have fell"},
		{time = 31.6, text = "It's time to take back the throne"},

		{time = 123.7, text = "MUZZ - Get Crazy"},
		{time = 152.5, text = "We all go crazy, we all go crazy"},
		{time = 158.7, text = "Crazy, crazy, crazy, crazy"},
		{time = 163.1, text = "We all go crazy"},
		{time = 174.1, text = "Comin' on the bassline"},
		{time = 175.5, text = "We all go crazy, we all go crazy"},
		{time = 181.0, text = "Crazy, crazy, crazy, crazy"},
		{time = 219.4, text = "We all go crazy, we all go crazy"},
		{time = 224.9, text = "Crazy, crazy, crazy"},

		{time = 227.0, text = "MUZZ - Play (ft. UK:ID)"},
		{time = 228.6, text = "We bring the dirt"},
		{time = 230.0, text = "We'll take you higher"},
		{time = 231.3, text = "We bring the heat, we bring the fire"},
		{time = 234.0, text = "We bring the dirt, we'll take you higher"},
		{time = 236.8, text = "We bring the heat, we bring the fire"},
		{time = 239.6, text = "We bring the dirt, we'll take you higher"},
		{time = 242.3, text = "We fill the place with our entire"},
		{time = 245.1, text = "Face-splittin', bass-driven, gunfire"},
		{time = 248.5, text = "I've been waiting for so long"},
		{time = 251.2, text = "Now the feelings are so gone"},
		{time = 254.0, text = "I don't care what else goes on"},
		{time = 256.4, text = "We will take you away"},
		{time = 259.4, text = "In the night when you see me"},
		{time = 262.2, text = "And I'm feeling free"},
		{time = 265.2, text = "Leave me to play"},
		{time = 287.3, text = "Leave me to play"},

		{time = 299.5, text = "MUZZ - Junction Seven"},
		{time = 366.6, text = "Calling all System 13s"},
		{time = 369.1, text = "We're cranking up the temperature"},
		{time = 371.2, text = "Brace yourselves"},
		{time = 373.0, text = "It's going to be a bumpy ride"},
		{time = 437.6, text = "Calling all System 13s"},
		{time = 440.0, text = "Your working day is complete"},
		{time = 442.5, text = "Please return to your vessels"},
		{time = 444.9, text = "The factory is going into shutdown"},
	},
	["npst_musicv13_1.mp3"] = {
		{time = 95.2, text = "I never stood a chance"},
		{time = 99.1, text = "My heart has frozen over"},
		{time = 102.1, text = "And I feel like I am treading on thin ice"},
		{time = 106.4, text = "And I'm going under"},
		{time = 108.8, text = "I need a cure for me 'cause the square doesn't fit the circle"},
		{time = 114.8, text = "Give me a remedy 'cause my head wasn't wired for this world"},
		{time = 121.0, text = "I need a cure for me 'cause the square doesn't fit the circle"},
		{time = 126.8, text = "Give me a remedy 'cause when it hits"},
		{time = 130.6, text = "Well, it hits like an avalanche"},
	},
	["npst_musicv13_1bis.mp3"] = {
		{time = 96.9, text = "Lead me through the guiding lights, through the signals in the darkness"},
		{time = 103.1, text = "Lead me through the northern stars, away from the madness"},
		{time = 108.4, text = "Just take me here, don't let them bring me under"},
		{time = 114.5, text = "Show me the way out of the dark, out of the night"},
		{time = 120.7, text = "(I see the signals in the dark, I see the signals)"},
		{time = 126.9, text = "(I see the signals in the dark)"},
	},
	["npst_musicv13_4.mp3"] = {
		{time = 212.2, text = "I'm sick of it"},
		{time = 213.8, text = "Of everything"},
		{time = 215.1, text = "My life is a dead end"},
		{time = 216.5, text = "I'm trapped within"},
		{time = 217.9, text = "Dreams destroyed"},
		{time = 219.3, text = "My hope is gone"},
		{time = 220.9, text = "Now, I am"},
		{time = 223.4, text = "I'm lost"},
		{time = 225.4, text = "Inside"},
		{time = 228.3, text = "A sea..."},
		{time = 231.8, text = "A sea... of burning tears..."},
		{time = 237.6, text = "of burning tears..."},
		{time = 243.2, text = "of burning tears..."},
		{time = 251.9, text = "Sea... of burning tears..."},
	},
	["npst_musicv13_7.mp3"] = {
		{time = 13.0, text = "MUZZ - Start Again (Lexurus & Dualistic Remix)"},
		{time = 18.2, text = "Come with me"},
		{time = 20.3, text = "We're gonna tear it down and start again"},
		{time = 23.5, text = "Come with me"},
		{time = 25.9, text = "'Cause we're never going back again"},
		{time = 28.9, text = "Come with me 'cause you're all I need"},
		{time = 31.8, text = "We're gonna tear it all down and start again"},

		{time = 80.0, text = "MUZZ - The Warehouse (ft. PAV4N & Miss Trouble)"},
		{time = 96.1, text = "People power"},
		{time = 101.5, text = "Like a renegade"},
		{time = 118.2, text = "The warehouse"},
		{time = 134.6, text = "The warehouse"},
		{time = 140.1, text = "The warehouse"},

		{time = 150.0, text = "RIOT - Down with Your Love (REAPER Remix)"},
		{time = 153.2, text = "You take me higher, baby"},
		{time = 155.2, text = "We down with your love"},
		{time = 156.7, text = "We down with your love, got me down with your love"},
		{time = 158.7, text = "You take me higher, baby"},
		{time = 160.8, text = "We down with your love"},
		{time = 162.0, text = "We down with your love, got me down with your love"},
		{time = 164.7, text = "Higher baby~"},
		{time = 186.3, text = "You take me higher baby~"},
		{time = 208.2, text = "You take me higher baby~"},
		{time = 219.4, text = "You take me higher baby~"},
	},
	["npst_musicv13_8.mp3"] = {
		{time = 19.4, text = "Was it worth the lie?"},
		{time = 41.2, text = "Was it worth the lie?"},
		{time = 54.7, text = "Everything's the same now"},
		{time = 57.4, text = "And you can give it to me"},
		{time = 60.1, text = "This is where the line draws"},
		{time = 62.9, text = "Love becomes the enemy"},
		{time = 65.4, text = "Causes to explain it"},
		{time = 68.4, text = "Never gonna get so far"},
		{time = 70.8, text = "Now, as I say goodbye"},
		{time = 73.6, text = "Tell me, was it worth the lie?"},
		{time = 83.6, text = "Was it worth the lie?"},
		{time = 93.9, text = "Tell me was it worth the lie?"},
	},
	["npst_musicv13_9.mp3"] = {
		{time = 5.0, text = "MUZZ & Delta Heavy - Revenge (Reaper Remix)"},
		{time = 46.9, text = "The founders of humanity told of an ancient beast"},
		{time = 51.7, text = "Resurrected from the dead"},
		{time = 54.5, text = "Hungry for revenge"},

		{time = 222.3, text = "MUZZ - Lost Forever"},
		{time = 225.3, text = "We're lost forever"},
		{time = 232.1, text = "We're lost forever"},
		{time = 237.8, text = "So take hold of my hand and we'll run till the end"},
		{time = 240.3, text = "We're like animals in the dark"},

		{time = 243.2, text = "MUZZ - Spectrum"},
		{time = 244.5, text = "We can see you through the end"},
		{time = 250.3, text = "Always wrong always undermined"},
		{time = 255.6, text = "Let the shadows fade away"},
		{time = 258.6, text = "And come with me inside"},
		{time = 264.8, text = "And we're lost forever"},

		{time = 309.2, text = "MUZZ & Flite - Elevate (ft. Miss Trouble)"},
		{time = 332.2, text = "Run for a cover"},
		{time = 333.8, text = "Hear my tribe roar alive with the thunder"},
		{time = 336.6, text = "Let it rain down, so we pull out another"},
		{time = 339.3, text = "All I want to feel is light we reveal"},
		{time = 341.7, text = "And the ceilings, roofs get blown with the feels"},
		{time = 344.8, text = "And the foundation lay down for the brave"},
		{time = 347.5, text = "Uncharted, we set the pace"},
		{time = 349.9, text = "Syncopated in the way we saying rise, elevate"},
		{time = 354.5, text = "Elevate"},
		{time = 360.2, text = "Elevate"},
		{time = 365.4, text = "Elevate"},
		{time = 371.0, text = "Elevate"},
		{time = 375.5, text = "Walk with your head up. High from the ghetto"},
		{time = 398.4, text = "Seeking the format. Smack that stiletto"},
		{time = 401.0, text = "Boosting the treble. Right that's the cutoff"},
		{time = 403.5, text = "All I want to feel is bass, slide make it wetter"},
	},
}