GM.ZELyrics = {
	["npst_music_6.mp3"] = {
		{time = 1.0, text = "MUZZ - Children of Hell"},
		{time = 12.5, text = "We're working"},
		{time = 15.2, text = "In shackles again"},
		{time = 17.9, text = "The end of a trend"},
		{time = 20.6, text = "The world descends"},
		{time = 22.8, text = "Until we're nothing"},
		{time = 25.9, text = "But the children of hell"},
		{time = 28.9, text = "The angels have fell"},
		{time = 31.6, text = "It's time to take back the throne"},

		{time = 123.7, text = "MUZZ - Get Crazy"},
		{time = 152.5, text = "We all go crazy, we all go crazy"},
		{time = 158.7, text = "Crazy, crazy, crazy, crazy"},
		{time = 163.1, text = "We all go crazy"},
		{time = 174.1, text = "Comin' on the bassline"},
		{time = 175.5, text = "We all go crazy, we all go crazy"},
		{time = 181.0, text = "Crazy, crazy, crazy, crazy"},
		{time = 219.4, text = "We all go crazy, we all go crazy"},
		{time = 224.9, text = "Crazy, crazy, crazy"},

		{time = 227.0, text = "MUZZ - Play (ft. UK:ID)"},
		{time = 228.6, text = "We bring the dirt"},
		{time = 230.0, text = "We'll take you higher"},
		{time = 231.3, text = "We bring the heat, we bring the fire"},
		{time = 234.0, text = "We bring the dirt, we'll take you higher"},
		{time = 236.8, text = "We bring the heat, we bring the fire"},
		{time = 239.6, text = "We bring the dirt, we'll take you higher"},
		{time = 242.3, text = "We fill the place with our entire"},
		{time = 245.1, text = "Face-splittin', bass-driven, gunfire"},
		{time = 248.5, text = "I've been waiting for so long"},
		{time = 251.2, text = "Now the feelings are so gone"},
		{time = 254.0, text = "I don't care what else goes on"},
		{time = 256.4, text = "We will take you away"},
		{time = 259.4, text = "In the night when you see me"},
		{time = 262.2, text = "And I'm feeling free"},
		{time = 265.2, text = "Leave me to play"},
		{time = 287.3, text = "Leave me to play"},

		{time = 299.5, text = "MUZZ - Junction Seven"},
		{time = 366.6, text = "Calling all System 13s"},
		{time = 369.1, text = "We're cranking up the temperature"},
		{time = 371.2, text = "Brace yourselves"},
		{time = 373.0, text = "It's going to be a bumpy ride"},
		{time = 437.6, text = "Calling all System 13s"},
		{time = 440.0, text = "Your working day is complete"},
		{time = 442.5, text = "Please return to your vessels"},
		{time = 444.9, text = "The factory is going into shutdown"},
	},
	["npst_music_1.mp3"] = {
		{time = 43.0, text = "You can hide your eyes, you can dim the lights, but they are watching"},
		{time = 48.4, text = "This is a new time with a different kind, they are the future"},
		{time = 53.5, text = "The only one"},
	},
	["npst_music_5.mp3"] = {
		{time = 25.8, text = "You can hide your eyes, you can dim the lights, but they are watching"},
		{time = 31.0, text = "This is a new time with a different kind, they are the future"},
		{time = 36.2, text = "The only one"},

		{time = 42.1, text = "It's a final call for the setting sun when they get closer"},
		{time = 47.7, text = "And with a fall from grace they will be done, the show is over"},
		{time = 52.5, text = "It's a new dawn"},

		{time = 64.2, text = "Just leave this place behind"},
		{time = 67.2, text = "I'll clear your bloodshot mind"},
		{time = 69.9, text = "They only wanted your life on demand"},
		{time = 74.4, text = "This is a better way"},

		{time = 100.9, text = "When all your fears combined"},
		{time = 103.7, text = "The manifest was refined"},
		{time = 106.5, text = "I know you really tried to understand"},
		{time = 111.2, text = "This is a new way"},
	},
}