GM.ZELyrics = {
	["w1music.mp3"] = {
		{time = 0, text = "Pendulum - Genesis"},
		{time = 60, text = "Pendulum - Crush"},
		{time = 88, text = "I was running out in the cold light"},
		{time = 91.9, text = "Wondering where to go"},
		{time = 94, text = "To run away without you"},
		{time = 99.6, text = "All my fear is coming home"},
		{time = 102.5, text = "Handing scripts out for the show"},
		{time = 105.2, text = "You can't be me, I will become you tonight"},
		{time = 111.5, text = "Bridges I've been dreamin' are coming down"},
		{time = 116.6, text = "They're changin' my future"},
		{time = 112.2, text = "Visions I had buried underground"},
		{time = 127.6, text = "Return as abusers"},
		{time = 143.7, text = "I was wandering under black skies"},
		{time = 147.2, text = "Clutching at what is mine"},
		{time = 149.4, text = "No control left to lose"},
		{time = 154.9, text = "Well, I thought that it wouldn't faze me"},
		{time = 157.8, text = "But I'm running like a child"},
		{time = 160.3, text = "I feel so guilty, I'll make it up to you tonight"},
		{time = 166.7, text = "The bridges I've been dreaming are coming down"},
		{time = 171.8, text = "They're changin' my future"},
		{time = 177.3, text = "Visions I had buried underground"},
		{time = 182.8, text = "Return as abusers"},
		{time = 199.5, text = "Well, the nightmares I've been havin' have arrived"},
		{time = 204.9, text = "They're changin' my future"},
		{time = 210.7, text = "Signs of my creation at my door"},
		{time = 215.3, text = "How could you do this to her?"},
		{time = 221.9, text = "Bridges I've been dreamin' are coming down"},
		{time = 227, text = "They're changin' my future"},
		{time = 232.5, text = "Visions I had buried underground"},
		{time = 237.9, text = "Return as abusers"}
	},
	["w2_tarantula.mp3"] = {
		{time = 21.4, text = "Black tarantula"},
		{time = 23.5, text = "Time for the massive come sing ya"},
		{time = 27.2, text = "Black tarantula"},
		{time = 28.9, text = "Don't play with my style I might sting ya"},
		{time = 32.8, text = "Black tarantula"},
		{time = 34.5, text = "You want me inject me bacteria"},
		{time = 38.3, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 42.5, text = "Now come fi get some..."},
		{time = 49.8, text = "Shotta, hitter, serial killer"},
		{time = 52.5, text = "Go-a your funeral and all drink out your liquor"},
		{time = 55.3, text = "When you are bury we a-stand next to vicar"},
		{time = 58, text = "Fling on some dirt and make your bury a little quicker"},
		{time = 60.8, text = "Shouldn't test the youth them in the Tommy Hilfiger"},
		{time = 63.6, text = "Hug up ya mama, say sorry to ya poppa"},
		{time = 66.3, text = "All-a get number for ya little sister "},
		{time = 69.1, text = "I true be cold like Alaska freezer"},
		{time = 71.5, text = "Black tarantula"},
		{time = 73.2, text = "Time for the massive come sing ya"},
		{time = 77, text = "Black tarantula"},
		{time = 78.5, text = "Don't play with my style I might sting ya"},
		{time = 82.3, text = "Black tarantula"},
		{time = 84.2, text = "You want me inject me bacteria"},
		{time = 87.9, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 92.2, text = "Now come fi get some..."},
		{time = 116, text = "Shotta, hitter, serial killer"},
		{time = 118.7, text = "Go-a your funeral and all drink out your liquor"},
		{time = 121.5, text = "When you are bury we a-stand next to the vicar"},
		{time = 124.2, text = "Fling on some dirt and make your bury a little quicker"},
		{time = 126.9, text = "Shouldn't test the youth them in the Tommy Hilfiger"},
		{time = 129.8, text = "Hug up ya mama, say sorry to ya poppa"},
		{time = 132.5, text = "All-a get number for ya little sister"},
		{time = 135.3, text = "I true be cold like Alaska freezer"},
		{time = 137.9, text = "Black tarantula"},
		{time = 139.5, text = "Time for the massive come sing ya"},
		{time = 143.2, text = "Black tarantula"},
		{time = 144.7, text = "Don't play with my style I might sting ya"},
		{time = 148.6, text = "Black tarantula"},
		{time = 150.4, text = "You want me inject me bacteria"},
		{time = 154.1, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 158.4, text = "Now come fi get some..."},
		{time = 204.3, text = "Shotta, hitter, serial killer"},
		{time = 207, text = "Go-a your funeral and all drink out your liquor"},
		{time = 209.7, text = "When you are bury we a-stand next to the vicar"},
		{time = 212.5, text = "Fling on some dirt and make your bury a little quicker"},
		{time = 215.3, text = "Shouldn't test the youth them in the Tommy Hilfiger"},
		{time = 218.1, text = "Hug up ya mama, say sorry to ya poppa"},
		{time = 220.8, text = "All-a get number for ya little sister"},
		{time = 223.6, text = "I true be cold like Alaska freezer"},
		{time = 226, text = "Black tarantula"},
		{time = 227.7, text = "Time for the massive come sing ya"},
		{time = 231.4, text = "Black tarantula"},
		{time = 233.1, text = "Don't play with my style I might sting ya"},
		{time = 236.9, text = "Black tarantula"},
		{time = 238.7, text = "You want me inject me bacteria"},
		{time = 242.3, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 246.7, text = "Now come fi get some..."},
		{time = 270.2, text = "Black tarantula"},
		{time = 271.9, text = "Time for the massive come sing ya"},
		{time = 275.3, text = "Black tarantula"},
		{time = 277.1, text = "Don't play with my style I might sting ya"},
		{time = 281, text = "Black tarantula"},
		{time = 282.8, text = "You want me inject me bacteria"},
		{time = 286.6, text = "And if ya body goin' stiff and your spine goin' numb"},
		{time = 290.8, text = "Now come fi get some... "}
	},
	["w3_invadersmustdie.mp3"] = {
		{time = 47.4, text = "We are The Prodigy"},
		{time = 92, text = "Invaders must die"},
		{time = 107.6, text = "Invaders must die"},
		{time = 111.2, text = "Invaders must die"},
		{time = 114.5, text = "Invaders must die"},
		{time = 118, text = "Invaders must die"},
		{time = 121.5, text = "Invaders must die"},
		{time = 124.9, text = "Invaders must die"},
		{time = 128.2, text = "Invaders must die"},
		{time = 131.8, text = "Invaders must die"},
		{time = 236.2, text = "We are The Prodigy"},
		{time = 249.9, text = "Invaders must die"}
	},
	["w6_pendulum_the_other_side_a.mp3"] = {
		{time = .3, text = "Come on down to the other side"},
		{time = 3.8, text = "Come with us through the gates of hell"},
		{time = 7.3, text = "We will drag you from where you are"},
		{time = 10.9, text = "To where you belong"},
		{time = 14.3, text = "Come on down to the other side"},
		{time = 17.7, text = "Come with us through the gates of hell"},
		{time = 21.2, text = "We will drag you from where you are"},
		{time = 24.9, text = "To where you belong"},
		{time = 28.9, text = "There's nothing to fear"},
		{time = 32.3, text = "Your saviors are here"},
		{time = 35.7, text = "This ship is coming down", autohold = true},
		{time = 40.3, text = "This ship is coming down, coming down"},
		{time = 41.8, text = "This ship is coming down, coming down, coming down"},
		{time = 42.9, text = "You, you are so precious"},
		{time = 46.6, text = "A diamond in the rough"},
		{time = 49.3, text = "And when you try to escape"},
		{time = 52, text = "I'll be holding on"},
		{time = 53.9, text = "(Holding on)"},
		{time = 54.7, text = "(Holding on, holding on)"},
		{time = 55.6, text = "(Holding on, holding on, holding on...)"},
		{time = 57.5, text = "But I can't sleep until this is done"},
	},
	["w6_selfvsself.mp3"] = {
		{time = 67.5, text = "If I struggle a lifetime"},
		{time = 70.6, text = "What would my body be?"},
		{time = 73.4, text = "An empty shell"},
		{time = 75.6, text = "On which a demon fed"},
		{time = 78.6, text = "Could be a heavy burden"},
		{time = 81.1, text = "To stay true to your words"},
		{time = 84.6, text = "Speak up"},
		{time = 86.5, text = "I wanna silence everything"},
		{time = 90.2, text = "If I got no plan"},
		{time = 95.4, text = "Doesn't mean that I get what I want for free"},
		{time = 101.3, text = "If I got no meaning"},
		{time = 106.7, text = "Would you force me to a place where I make sense"},
		{time = 111.7, text = "'Cause nothing lasts forever!"},
		{time = 116.5, text = "How do I get home?"},
		{time = 119.8, text = "Everything revolves around me"},
		{time = 121.7, text = "If I can't find myself?"},
		{time = 125.1, text = "It's so completely fake"},
		{time = 127.5, text = "How do I get home?"},
		{time = 131, text = "Everything revolves around me"},
		{time = 132.9, text = "If even you can't help?"},
		{time = 137.3, text = "Dark nights on my soul"},
		{time = 162.4, text = "I deny failure"},
		{time = 164.7, text = "I ignite"},
		{time = 166.8, text = "Woe is on my misery"},
		{time = 169.4, text = "She wins all their eyes"},
		{time = 172.3, text = "Realise what defies our fate"},
		{time = 175.3, text = "This is not me, this is me"},
		{time = 178, text = "So if I struggle a lifetime"},
		{time = 180.7, text = "What good would that do?"},
		{time = 184.2, text = "If I got a plan"},
		{time = 189.6, text = "Doesn't have to stop the feeling inside"},
		{time = 195.1, text = "If I do make sense"},
		{time = 200.6, text = "Would you drag me down?"},
		{time = 205.2, text = "'Cause nothing lasts forever!"},
		{time = 232.5, text = "How do I get home?"},
		{time = 235.4, text = "Everything revolves around me"},
		{ime = 238.1, text = "If I can't find myself?"},
		{time = 241, text = "It's so completely fake"},
		{time = 243.6, text = "How do I get home?"},
		{time = 246.7, text = "Everything revolves around me"},
		{time = 248.8, text = "If even you can't help?"},
		{time = 253, text = "Dark nights on my soul"}
	},
	["w7_end_bad_end.mp3"] = {
		{time = 1.1, text = "For everything that could have been"},
		{time = 6.8, text = "Well, at least we took the ride"},
		{time = 12, text = "There's no relief in bitterness"},
		{time = 17.5, text = "Might as well let it die"},
		{time = 22.5, text = "For everything that could have been"},
		{time = 33.5, text = "There's no relief in bitterness"},
		{time = 49.4, text = "Well, at least we took the ride"},
		{time = 60.3, text = "Might as well let it die"}
	},
	["w7_stage_5_start.mp3"] = {
		{time = 23.00, text = "Your last chance"},
		{time = 26.00, text = "Last summer"},
		{time = 29.00, text = "Your last dance"},
		{time = 31.00, text = "To beat to your own drummer"},
		{time = 35.00, text = "Go out fighting"},
		{time = 37.00, text = "Go out young"},
		{time = 40.00, text = "A flash of lightning"},
		{time = 43.00, text = "Eclipse the sun"},
		{time = 45.00, text = "Your last chance"},
		{time = 49.00, text = "Last summer"},
		{time = 51.00, text = "Your last dance"},
		{time = 54.00, text = "To beat to your own drummer"},
		{time = 57.00, text = "Go out fighting"},
		{time = 60.00, text = "Go out young"},
		{time = 62.00, text = "A flash of lightning"},
		{time = 65.00, text = "Eclipse the sun"},
		{time = 67.00, text = "Brace yourself brace yourself"},
		{time = 87.00, text = "Brace yourself for the grand finale"},
		{time = 91.00, text = "Whoa oh~~~"},
		{time = 131.00, text = "Brace yourself for the grand finale"},
		{time = 156.00, text = "Your last chance"},
		{time = 159.00, text = "Last summer"},
		{time = 162.00, text = "Your last dance"},
		{time = 164.00, text = "To beat to your own drummer"},
		{time = 168.00, text = "Go out fighting"},
		{time = 171.00, text = "Go out young"},
		{time = 173.00, text = "A flash of lightning"},
		{time = 176.00, text = "Eclipse the sun"},
		{time = 178.00, text = "Brace yourself brace yourself"},
		{time = 198.00, text = "Brace yourself for the grand finale"},
		{time = 202.00, text = "Whoah oh~~~"},
		{time = 242.00, text = "Brace yourself for the grand finale"},
	},
	["w7_stage_5_top.mp3"] = {
		{time = 11.00, text = "It's in your eyes, a color fade-out"},
		{time = 17.00, text = "Looks like a new transition"},
		{time = 22.00, text = "Is starting up and shaking your ground"},
		{time = 27.7, text = "Turning your head to see a new day calling"},
		{time = 34.8, text = "Does it feel like a head to lean on"},
		{time = 40.4, text = "A snapshot from where you were born"},
		{time = 45.1, text = "I'm looking for your hand in the rought"},
		{time = 49.00, text = "You're caught in the wire"},
		{time = 52.40, text = "Well I'll life you out"},
		{time = 55.30, text = "When I'm falling down"},
		{time = 60.90, text = "Will you pick me up again"},
		{time = 67.10, text = "When I'm too far gone"},
		{time = 72.20, text = "Dead in the eys of my friends"},
		{time = 77.80, text = "Will you take me out of here"},
		{time = 80.80, text = "When I'm staring down the barrel"},
		{time = 83.60, text = "When I'm blinded by the lights"},
		{time = 86.40, text = "When I cannot see your face"},
		{time = 89.70, text = "Take me out of here", autohold = true},
		{time = 99.00, text = "Leaning on the action"},
		{time = 101.70, text = "Caught in a cellphone's rays"},
		{time = 104.60, text = "Bleeding on the sofa"},
		{time = 107.20, text = "Staring at the wayside"},
		{time = 109.80, text = "He's coming and she knows it"},
		{time = 112.7, text = "Even if she knows why"},
		{time = 115.20, text = "Footsetps in the hallway"},
		{time = 118.30, text = "Girl you haven't got time"},
		{time = 120.00, text = "All I believe"},
		{time = 123.00, text = "And all I've known"},
		{time = 125.30, text = "Are being taken from me"},
		{time = 128.70, text = "Can't get home"},
		{time = 131.00, text = "Led to a world"},
		{time = 134.00, text = "When worlds collide"},
		{time = 137, text = "Let the fear collapse bring no surprise"},
		{time = 142.30, text = "Take me out of here"},
		{time = 164.50, text = "Feed the fire, break your vision"},
		{time = 167.00, text = "Throw your fists up come on with me"},
		-- dunno how this shoud be handled considering its both endinigs overlapping
	},
}